#!/usr/bin/env python3
"""Extracts the reference's preset migration into `reference_migration.inc`.

`LoadSave::updateFromOldVersion` (load_save.cpp) is JSON in, JSON out —
no DSP, nothing to interpret — but the file it lives in needs JUCE
(`File`, `MemoryBlock`, `FileInputStream`, `SynthBase`). So the function
and the two PCM converters it calls are copied out VERBATIM by this
script, wrapped in a `ReferenceLoad` namespace, and compiled into the
harness. Run it when the reference source changes; the harness build
does not depend on it, the committed `.inc` is what compiles.

    python tools/golden/extract_migration.py [path-to-vital/src]
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
src = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser("~/vital-reference/src")
text = open(os.path.join(src, "common", "load_save.cpp"), encoding="utf-8").read()


def function(signature):
    start = text.index(signature)
    # the function body ends at the first "\n}\n" after the signature
    end = text.index("\n}\n", start) + 3
    return text[start:end]


parts = [
    function("void LoadSave::convertBufferToPcm(json& data, const std::string& field) {"),
    function("void LoadSave::convertPcmToFloatBuffer(json& data, const std::string& field) {"),
    function("json LoadSave::updateFromOldVersion(json state) {"),
]
body = "\n".join(parts)
# Verbatim: the `LoadSave` class they belong to is declared by the
# stub's load_save.h, with the two version comparators (JUCE String
# code) reimplemented in reference_load.cpp.
lines = text.count("\n", 0, text.index("json LoadSave::updateFromOldVersion(json state) {")) + 1
header = f"""// GENERATED by tools/golden/extract_migration.py from the reference's
// src/common/load_save.cpp (updateFromOldVersion at line {lines}, plus the
// two PCM converters it calls), verbatim. Do not edit; re-run the script.
"""
open(os.path.join(HERE, "reference_migration.inc"), "w", encoding="utf-8", newline="\n").write(header + body)
print(f"wrote reference_migration.inc ({body.count(chr(10))} lines)")
