#!/usr/bin/env python3
"""Writes the golden corpus: one case per thing worth pinning down.

Cases are small and mechanical, so they are generated rather than typed:
a table here beats forty near-identical files drifting apart by hand. Run
this whenever the corpus grows, then regenerate the references:

    python tools/golden/make_cases.py
    for c in tools/golden/cases/*.txt; do
        tools/golden/build/vital_golden "$c" \
            "tools/golden/reference/$(basename "${c%.txt}").raw"
    done

Two rules every case obeys, both learned the hard way:

* `random_phase 0` is mandatory. It defaults to 1, and two engines cannot
  agree sample for sample on a waveform that starts somewhere random.

* The first note is a primer that `skip` excludes. The reference scoops
  its very first note up from MIDI note 0 (its last-played-note starts at
  zero), which Spinwave deliberately does not reproduce; see the note in
  spinwave-engine/src/allocator.rs. Skipping the glide alone is not
  enough, because it leaves the two oscillators a fixed phase apart, so
  the primer has to be a whole note the next one resets the phase from.
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))
CASES = os.path.join(HERE, "cases")

PREAMBLE = """\
# {title}
#
# Generated by tools/golden/make_cases.py; edit that, not this.
rate 44100
seconds {seconds}
skip {skip}
wave {wave}
set osc_1_on 1
set osc_1_level 0.7
set osc_1_random_phase 0
set osc_1_phase 0
"""

FOOTER = """\
note 45 0.9 0.0 0.3
note {note} 0.9 {start} 0.6
"""

# The primer note differs between the two engines by construction (the
# reference glides it from MIDI 0), and `skip` hides it — but not its
# ECHO: a delay of 250 ms with feedback 0.5 brings the primer back into
# the compared window at 0.5^4, and a reverb's tail lasts seconds.
# fx_delay's 1.4e-2 and fx_reverb's 6.4e-3 were the primer's echo, not
# the effect. A case with a delay line or a reverb skips 5 s instead of
# 1 (0.5^20 = 1e-6 for the delay; a 1 s decay is -240 dB by then).
LONG_SKIP = 5.0


def case(name, title, settings, wave="saw", note=45, modulations=(), extra_notes=(),
         random_seed=None, skip=1.0):
    """One case: a preamble, the settings under test, the two notes.

    `extra_notes` adds `(midi, velocity, start, hold)` events on top, for
    the cases that need more than one voice sounding at a time.
    `random_seed` pins the Spinwave side's random LFO seed to the one the
    reference's construction order gives it (see random_seed.py).
    """
    body = PREAMBLE.format(title=title, wave=wave, seconds=skip + 1.0, skip=skip)
    for key, value in settings:
        body += "set {} {}\n".format(key, value)
    for slot, modulation in enumerate(modulations, start=1):
        source, destination, amount = modulation[:3]
        flags = modulation[3] if len(modulation) > 3 else {}
        body += "modulate {} {} {}\n".format(source, destination, amount)
        # Every connection states its polarity. The reference creates a
        # NEW connection bipolar when the source is an lfo / random /
        # stereo / pitch (kBipolarModulationSourcePrefixes), a fact that
        # cost a whole session while the harness relied on defaults; a
        # case that means unipolar says so, on every slot.
        body += "set modulation_{}_bipolar {}\n".format(slot, flags.get("bipolar", 0))
        for key in ("power", "stereo", "bypass"):
            if key in flags:
                body += "set modulation_{}_{} {}\n".format(slot, key, flags[key])
    if random_seed is not None:
        body += "random_seed {}\n".format(random_seed)
    body += FOOTER.format(note=note, start=skip + 0.1)
    for midi, velocity, start, hold in extra_notes:
        body += "note {} {} {} {}\n".format(midi, velocity, start + skip - 1.0, hold)
    with open(os.path.join(CASES, name + ".txt"), "w", newline="\n") as out:
        out.write(body)


# -- The corpus --------------------------------------------------------------

# The plain path first: if this diverges, nothing below means anything.
case("osc_saw_dry", "A bare saw: no filter, no effects, no modulation",
     [("filter_1_on", 0)])

# Every waveform the reference ships, through the same bare path. These
# pin the oscillator's band-limiting and its wavetable reading.
for wave in ("sin", "triangle", "square", "pulse"):
    case("osc_wave_" + wave, "A bare {} through the plain path".format(wave),
         [("filter_1_on", 0)], wave=wave)

# Phase distortion: the shapes that make Vital sound like Vital. Amount is
# held at 0.6 so each mode is doing real work rather than sitting near its
# neutral point.
PHASE_MODES = [
    (1, "sync"), (2, "formant"), (3, "quantize"), (4, "bend"),
    (5, "squeeze"), (6, "pulse_width"), (7, "fm_from_a"), (8, "fm_from_b"),
    (9, "rm_from_a"), (10, "rm_from_b"), (11, "phase_disperse"), (12, "fm_a_b"),
]
for index, name in PHASE_MODES:
    case("osc_warp_" + name,
         "Phase distortion mode {} ({})".format(index, name),
         [("filter_1_on", 0),
          ("osc_1_distortion_type", index),
          ("osc_1_distortion_amount", 0.6)])

# Spectral morphs, same idea: each mode at a working amount.
MORPH_MODES = [
    (1, "vocode"), (2, "formant_scale"), (3, "harmonic_stretch"),
    (4, "inharmonic_stretch"), (5, "smear"), (6, "random_amplitudes"),
    (7, "low_pass"), (8, "high_pass"), (9, "phase_disperse"),
    (10, "shepard"), (11, "spectral_time_skew"),
]
for index, name in MORPH_MODES:
    case("osc_morph_" + name,
         "Spectral morph mode {} ({})".format(index, name),
         [("filter_1_on", 0),
          ("osc_1_spectral_morph_type", index),
          ("osc_1_spectral_morph_amount", 0.6)])

# Unison: the detune law, the stereo spread and the voice stacking.
case("osc_unison", "Seven-voice unison, wide detune",
     [("filter_1_on", 0),
      ("osc_1_unison_voices", 7),
      ("osc_1_unison_detune", 6.0),
      ("osc_1_unison_blend", 0.7),
      ("osc_1_stereo_spread", 0.8)])

# Filters: every model, twice. Low resonance shows the response, high
# resonance shows the saturator and the feedback path.
FILTER_MODELS = [
    (0, "analog"), (1, "dirty"), (2, "ladder"), (3, "digital"),
    (4, "diode"), (5, "formant"), (6, "comb"), (7, "phaser"),
]
for index, name in FILTER_MODELS:
    for resonance, label in ((0.3, "low_q"), (0.85, "high_q")):
        case("filter_{}_{}".format(name, label),
             "Filter model {} ({}) at resonance {}".format(index, name, resonance),
             [("filter_1_on", 1),
              ("filter_1_model", index),
              ("filter_1_cutoff", 72.0),
              ("filter_1_resonance", resonance),
              ("filter_1_drive", 6.0)])

# The formant filter's own controls, away from their defaults. The two
# cases above exercise the model at default X/Y; this one exercises the
# five controls the read-parameter audit found were never read from a
# preset (the DSP had them; the reader did not ask). Added 2026-09-12
# with the wiring, so it is the first measurement of them.
case("filter_formant_xy", "Formant filter with X, Y, transpose, resonance and spread moved",
     [("filter_1_on", 1), ("filter_1_model", 5),
      ("filter_1_formant_x", 0.15), ("filter_1_formant_y", 0.8),
      ("filter_1_formant_transpose", 4.0), ("filter_1_formant_resonance", 0.6),
      ("filter_1_formant_spread", 0.4)])

# An LFO in envelope mode (sync_type 2: one pass, then hold the end),
# the other control the audit found unread. A triangle that stops at its
# end is a ramp up then a plateau; the default trigger mode keeps cycling.
case("mod_lfo_envelope_mode", "LFO 1 in envelope (one-shot) mode to cutoff",
     [("filter_1_on", 1), ("filter_1_model", 3),
      ("filter_1_cutoff", 50.0), ("filter_1_resonance", 0.4),
      ("lfo_1_frequency", 0.0), ("lfo_1_sync", 0), ("lfo_1_sync_type", 2)],
     modulations=[("lfo_1", "filter_1_cutoff", 0.6)])

# Effects, one at a time, each with its dry/wet up so the effect is what
# the comparison is looking at.
EFFECTS = [
    ("chorus", [("chorus_dry_wet", 0.8)]),
    ("delay", [("delay_dry_wet", 0.8), ("delay_feedback", 0.5)]),
    ("distortion", [("distortion_drive", 12.0), ("distortion_mix", 1.0)]),
    ("eq", [("eq_low_gain", 8.0), ("eq_high_gain", -8.0)]),
    ("flanger", [("flanger_dry_wet", 0.4), ("flanger_feedback", 0.6)]),
    ("phaser", [("phaser_dry_wet", 0.8), ("phaser_feedback", 0.6)]),
    ("reverb", [("reverb_dry_wet", 0.8), ("reverb_decay_time", 1.0)]),
    ("compressor", [("compressor_mix", 1.0)]),
    ("filter_fx", [("filter_fx_cutoff", 70.0), ("filter_fx_resonance", 0.6)]),
]
for name, settings in EFFECTS:
    case("fx_" + name, "The {} effect on its own".format(name),
         [("filter_1_on", 0), (name + "_on", 1)] + settings,
         skip=LONG_SKIP if name in ("delay", "reverb") else 1.0)

# The compressor taken apart, for its ~1e-5 (2026-09-13): every ratio at
# zero leaves gain 1 through the polynomial pow, so the crossovers alone
# are heard; then a single band (no crossover) with the ratios on, so the
# envelope follower alone is heard.
ZERO_RATIOS = [("compressor_low_upper_ratio", 0.0), ("compressor_band_upper_ratio", 0.0),
               ("compressor_high_upper_ratio", 0.0), ("compressor_low_lower_ratio", 0.0),
               ("compressor_band_lower_ratio", 0.0), ("compressor_high_lower_ratio", 0.0),
               ("compressor_low_gain", 0.0), ("compressor_band_gain", 0.0), ("compressor_high_gain", 0.0)]
case("fx_compressor_crossover_only", "The compressor's three bands summed, ratios at zero",
     [("filter_1_on", 0), ("compressor_on", 1), ("compressor_mix", 1.0)] + ZERO_RATIOS)
case("fx_compressor_single_band", "The compressor on one band (no crossover), ratios on",
     [("filter_1_on", 0), ("compressor_on", 1), ("compressor_mix", 1.0), ("compressor_enabled_bands", 3)])
case("fx_compressor_single_band_flat", "One band, ratios at zero: the follower is inert",
     [("filter_1_on", 0), ("compressor_on", 1), ("compressor_mix", 1.0), ("compressor_enabled_bands", 3)] + ZERO_RATIOS)

# Every distortion type on its own, and the LFO on the drive of each:
# the downsample (type 5) holds a sample for a period the drive sets and
# keeps a counter with a fractional residual across blocks, so it hears
# anything the other types forget - the smoothed base of the seven
# audio-rate controls (fx_distortion_downsample: 2.4e-2 with the base
# stepped to its value at load, 8e-8 with the reference's SmoothValue
# glide from the default; 2026-09-13, night), and the primer's very
# first block (mod_lfo_to_downsample_drive, tracked: see golden.rs).
for kind, name in ((1, "hard_clip"), (2, "linear_fold"), (3, "sin_fold"), (4, "bit_crush"), (5, "downsample")):
    case("fx_distortion_" + name, "The distortion's {} on its own".format(name.replace("_", " ")),
         [("filter_1_on", 0), ("distortion_on", 1), ("distortion_type", kind),
          ("distortion_drive", 12.0), ("distortion_mix", 1.0)])
    case("mod_lfo_to_" + name + "_drive", "The LFO into the {}'s drive".format(name.replace("_", " ")),
         [("filter_1_on", 0), ("distortion_on", 1), ("distortion_type", kind), ("lfo_1_frequency", 3.0),
          ("distortion_drive", 6.0), ("distortion_mix", 1.0)],
         modulations=[("lfo_1", "distortion_drive", 0.3)])

# The distortion's own filter, unmodulated: the twin of
# mod_lfo_to_distortion_filter_cutoff below without the connection, so a
# residual shared by both belongs to the filter and not to the route.
for order, name in ((1, "pre"), (2, "post")):
    case("fx_distortion_filter_" + name, "The distortion's {}-filter on its own".format(name),
         [("filter_1_on", 0), ("distortion_on", 1),
          ("distortion_drive", 6.0), ("distortion_mix", 1.0),
          ("distortion_filter_order", order),
          ("distortion_filter_cutoff", 60.0), ("distortion_filter_resonance", 0.5)])

# Mono modulation into the effect chain. The reference creates six effect
# controls with `audio_rate = true` (distortion_drive,
# distortion_filter_cutoff, eq_low/band/high_cutoff, phaser_center,
# filter_fx_cutoff): their ModulationSum ramps the control-rate part
# across the block and adds audio-rate sources per sample. The LFO here
# is tempo-synced (the default; `lfo_1_frequency` is set but the sync
# ignores it - measured 2026-09-13: the reference renders of 2 Hz and
# 8 Hz are byte-identical), so it runs at 1 Hz at the harness's 120 BPM;
# the `_fast` twin below frees it at 32 Hz, where a one-block lag is
# 20 dB louder. distortion_mix is a CONTROL-rate destination on the same
# route, the control: if it fails too, the mono route is wrong, not the
# rate.
MONO_MOD = [
    ("distortion_mix", "distortion", [("distortion_drive", 6.0), ("distortion_mix", 0.5)], 0.4),
    ("distortion_drive", "distortion", [("distortion_drive", 6.0), ("distortion_mix", 1.0)], 0.3),
    ("distortion_filter_cutoff", "distortion",
     [("distortion_drive", 6.0), ("distortion_mix", 1.0), ("distortion_filter_order", 1),
      ("distortion_filter_cutoff", 60.0), ("distortion_filter_resonance", 0.5)], 0.3),
    ("eq_low_cutoff", "eq", [("eq_low_gain", 8.0), ("eq_low_cutoff", 60.0)], 0.3),
    ("phaser_center", "phaser", [("phaser_dry_wet", 0.8), ("phaser_feedback", 0.6)], 0.3),
    ("filter_fx_cutoff", "filter_fx", [("filter_fx_cutoff", 60.0), ("filter_fx_resonance", 0.5)], 0.4),
]
for destination, effect, settings, amount in MONO_MOD:
    case("mod_lfo_to_" + destination, "The (tempo-synced) LFO into " + destination,
         [("filter_1_on", 0), (effect + "_on", 1), ("lfo_1_frequency", 3.0)] + settings,
         modulations=[("lfo_1", destination, amount)])

# The filter fx reads its cutoff one block late in the reference (its
# FilterModule runs the filter before the control sum that feeds it, an
# insertion-order accident of the mono module; see
# EffectChain::process). A free 32 Hz LFO makes a one-block lag audible
# (rms 2.7e-2 without it, 1.6e-6 with), and the keytrack, part of the
# same sum, must lag the same block: the primer at 45 then a note at 57
# with full keytrack.
case("mod_lfo_to_filter_fx_cutoff_fast", "A free 32 Hz LFO into filter_fx_cutoff",
     [("filter_1_on", 0), ("filter_fx_on", 1), ("lfo_1_sync", 0), ("lfo_1_frequency", 5.0),
      ("filter_fx_cutoff", 60.0), ("filter_fx_resonance", 0.5)],
     modulations=[("lfo_1", "filter_fx_cutoff", 0.4)])
# A modulator into another modulator's parameter. The reference orders
# its voice processors by dependency, so lfo_1 with lfo_2 ->
# lfo_1_frequency runs after lfo_2 and integrates this block's value;
# resolving the parameters once per block after every modulator had
# run made it a block late (rms 2.9e-2 on the free-frequency case,
# 7.4e-3 on the tempo one, 2026-09-13), and the LFO's phase integrates
# the lag. A cycle (lfo_1 <-> lfo_2) gets no Feedback node in the
# reference (the module boundary hides it from the router's cycle
# check); the reordering leaves the connection listed first read a
# block late, the other the same block, and a note-on does not clear
# it (ModMatrix::compute_modulator_order).
MOD_TO_MOD = [
    ("lfo_to_lfo_frequency", [("lfo_1_sync", 0), ("lfo_1_frequency", 1.0), ("lfo_2_sync", 0), ("lfo_2_frequency", 1.0)],
     [("lfo_1", "filter_1_cutoff", 0.4), ("lfo_2", "lfo_1_frequency", 0.3)]),
    ("lfo_to_lfo_tempo", [("lfo_1_sync", 1), ("lfo_1_tempo", 6), ("lfo_2_sync", 0), ("lfo_2_frequency", 1.0)],
     [("lfo_1", "filter_1_cutoff", 0.4), ("lfo_2", "lfo_1_tempo", 0.3)]),
    ("lfo_to_lfo_tempo_bipolar", [("lfo_1_sync", 1), ("lfo_1_tempo", 6), ("lfo_2_sync", 0), ("lfo_2_frequency", 1.0)],
     [("lfo_1", "filter_1_cutoff", 0.4), ("lfo_2", "lfo_1_tempo", 0.3, {"bipolar": 1})]),
    ("env_to_lfo_frequency", [("lfo_1_sync", 0), ("lfo_1_frequency", 1.0), ("env_2_attack", 0.6), ("env_2_decay", 0.8)],
     [("lfo_1", "filter_1_cutoff", 0.4), ("env_2", "lfo_1_frequency", 0.5)]),
    ("lfo_to_env_attack", [("lfo_2_sync", 0), ("lfo_2_frequency", 1.0), ("env_2_attack", 0.5), ("env_2_sustain", 0.3)],
     [("env_2", "filter_1_cutoff", 0.4), ("lfo_2", "env_2_attack", 0.4)]),
    ("lfo_cycle", [("lfo_1_sync", 0), ("lfo_1_frequency", 1.0), ("lfo_2_sync", 0), ("lfo_2_frequency", 1.5)],
     [("lfo_1", "filter_1_cutoff", 0.4), ("lfo_2", "lfo_1_frequency", 0.3), ("lfo_1", "lfo_2_frequency", 0.3)]),
    # The same cycle with its two connections swapped: the reference's
    # renders differ by rms 5.7e-2 between the two orders (the earliest
    # listed connection of a cycle is the one read a block late), so
    # one case cannot stand for both.
    ("lfo_cycle_swapped", [("lfo_1_sync", 0), ("lfo_1_frequency", 1.0), ("lfo_2_sync", 0), ("lfo_2_frequency", 1.5)],
     [("lfo_1", "filter_1_cutoff", 0.4), ("lfo_1", "lfo_2_frequency", 0.3), ("lfo_2", "lfo_1_frequency", 0.3)]),
    # The order of the list decides more than cycles: a connection FROM
    # lfo_1 plugged after the one INTO lfo_1's phase pulls lfo_1 ahead of
    # it in the reference's router (the plug reorders the connection
    # behind its source module, which knows nothing of the totals plugged
    # inside it), and lfo_1 then reads its phase a block late. Thumpus
    # (1.6 dB with every modulator-parameter connection same-block) is
    # this shape: lfo_2 -> lfo_1_phase, then lfo_1 -> osc_2_wave_frame.
    ("lfo_phase_listed_first", [("lfo_1_sync", 0), ("lfo_1_frequency", 1.0), ("lfo_2_sync", 0), ("lfo_2_frequency", 1.0)],
     [("lfo_2", "lfo_1_phase", 1.0), ("lfo_1", "filter_1_cutoff", 0.4)]),
    ("lfo_phase_then_frame", [("lfo_1_sync", 0), ("lfo_1_frequency", 1.0), ("lfo_2_sync", 0), ("lfo_2_frequency", 1.0),
                              ("osc_2_on", 1), ("osc_2_level", 0.5), ("osc_2_random_phase", 0), ("osc_2_phase", 0)],
     [("lfo_1", "filter_1_cutoff", 0.4), ("lfo_2", "lfo_1_phase", 1.0), ("lfo_1", "osc_2_wave_frame", 0.5)]),
]
for name, settings, modulations in MOD_TO_MOD:
    case("mod_" + name, "A modulator into another's parameter: " + name.replace("_", " "),
         [("filter_1_on", 1), ("filter_1_model", 3), ("filter_1_cutoff", 60.0), ("filter_1_resonance", 0.4)] + settings,
         modulations=modulations)

# A pitch that keeps moving: an LFO sweeping the transpose two octaves,
# an envelope decaying it over half a second. Both sit at float noise
# against the Debug reference build (4.1e-8, 7.4e-8). They are here
# because a RELEASE build of the same reference reads 3.1e-4 and 2.1e-4
# on them: its float arithmetic differs by ulps, and a moving pitch
# integrates those into a phase offset that plateaus once the pitch
# settles (4.8e-3 peak). The lesson, 2026-09-13: the Release harness is
# fine for bisecting a preset (60x faster, 4e-6 on a static pad) and
# useless below 1e-3 on anything that sweeps a pitch; the goldens are
# the Debug build's, and so is the bank table.
case("mod_lfo_to_transpose_sweep", "An LFO sweeping osc 1's transpose two octaves",
     [("filter_1_on", 0), ("lfo_1_sync", 0), ("lfo_1_frequency", 1.0)],
     modulations=[("lfo_1", "osc_1_transpose", 0.5)])
case("mod_env_to_pitch_slow", "An envelope decaying the transpose over half a second",
     [("filter_1_on", 0), ("env_2_attack", 0.0), ("env_2_decay", 0.8), ("env_2_sustain", 0.0), ("env_2_release", 0.3)],
     modulations=[("env_2", "osc_1_transpose", 0.5)])

case("fx_filter_fx_keytrack", "The filter fx's keytrack, a note change under it",
     [("filter_1_on", 0), ("filter_fx_on", 1), ("filter_fx_cutoff", 60.0),
      ("filter_fx_resonance", 0.6), ("filter_fx_keytrack", 1.0)], note=57)

# -- The remaining mono destinations of the real bank (2026-09-13) ---------
#
# Every control the reference creates with createMonoModControl and the
# 75 presets modulate. Each gets a macro (a constant) with a static twin
# set to the value the macro should produce: identical references say
# the route and the scale are right without any reading of the code
# (the regime, per block on both sides, is the control-rate route that
# mod_lfo_to_distortion_mix already proves). Offsets add to the STORED
# value — before the square of a Quadratic control (eq resonances,
# reverb chorus amount) and before the exp2 of an Exponential one
# (chorus delays) — so the twin sets stored + macro × amount × range.
# Every value stays interior to its range (bounds.rs checks).
STEREO = [("osc_1_unison_voices", 4), ("osc_1_unison_detune", 2.0),
          ("osc_1_stereo_spread", 1.0)]
def mono_dest(destination, effect, settings, base, amount, range_, extra=()):
    macro = 0.5
    expected = base + macro * amount * range_
    common = [("filter_1_on", 0), (effect + "_on", 1), ("macro_control_1", macro)]
    common += list(extra)
    skip = LONG_SKIP if effect in ("delay", "reverb") else 1.0
    case("mono_macro_to_" + destination, "A macro into " + destination,
         common + settings + [(destination, base)],
         modulations=[("macro_control_1", destination, amount)], skip=skip)
    case("mono_macro_to_" + destination + "_static",
         "The value the macro should give " + destination + ", set statically",
         common + settings + [(destination, round(expected, 8))], skip=skip)

CHORUS = [("chorus_dry_wet", 0.5)]
mono_dest("chorus_delay_1", "chorus", CHORUS, -9.0, 0.2, 4.35614)
mono_dest("chorus_delay_2", "chorus", CHORUS, -7.0, -0.2, 4.35614)
mono_dest("chorus_cutoff", "chorus", CHORUS, 60.0, 0.1, 128.0)
mono_dest("chorus_spread", "chorus", CHORUS, 1.0, -0.3, 1.0)
mono_dest("chorus_tempo", "chorus", CHORUS + [("chorus_sync", 1)], 4.0, 0.5, 10.0)
FLANGER = [("flanger_dry_wet", 0.4), ("flanger_feedback", 0.6)]
mono_dest("flanger_center", "flanger", FLANGER, 64.0, 0.1, 128.0)
mono_dest("flanger_tempo", "flanger", FLANGER + [("flanger_sync", 1)], 4.0, 0.5, 10.0)
PHASER = [("phaser_dry_wet", 0.8), ("phaser_feedback", 0.6)]
mono_dest("phaser_phase_offset", "phaser", PHASER, 0.33333333, 0.2, 1.0)
mono_dest("phaser_tempo", "phaser", PHASER + [("phaser_sync", 1)], 3.0, 0.5, 10.0)
DELAY = [("delay_dry_wet", 0.5), ("delay_feedback", 0.5)]
mono_dest("delay_filter_cutoff", "delay", DELAY, 60.0, 0.1, 128.0)
mono_dest("delay_filter_spread", "delay", DELAY, 1.0, -0.3, 1.0)
mono_dest("delay_tempo", "delay", DELAY + [("delay_sync", 1)], 9.0, 0.25, 8.0)
mono_dest("delay_aux_tempo", "delay", DELAY + [("delay_style", 1), ("delay_aux_sync", 1)], 9.0, 0.25, 8.0)
DISTORTION = [("distortion_drive", 6.0), ("distortion_mix", 1.0), ("distortion_filter_order", 1),
              ("distortion_filter_cutoff", 60.0)]
mono_dest("distortion_filter_resonance", "distortion", DISTORTION, 0.5, 0.2, 1.0)
mono_dest("distortion_filter_blend", "distortion", DISTORTION, 0.0, 0.2, 2.0)
EQ = [("eq_low_gain", 8.0), ("eq_band_gain", -6.0), ("eq_high_gain", -8.0)]
mono_dest("eq_low_resonance", "eq", EQ, 0.3163, 0.2, 1.0)
mono_dest("eq_band_resonance", "eq", EQ, 0.4473, 0.2, 1.0)
mono_dest("eq_high_resonance", "eq", EQ, 0.3163, 0.2, 1.0)
COMPRESSOR = [("compressor_mix", 1.0)]
mono_dest("compressor_attack", "compressor", COMPRESSOR, 0.5, 0.2, 1.0)
mono_dest("compressor_release", "compressor", COMPRESSOR, 0.5, -0.2, 1.0)
REVERB = [("reverb_dry_wet", 0.5), ("reverb_decay_time", 0.0)]
mono_dest("reverb_delay", "reverb", REVERB, 0.0, 0.2, 0.3)
mono_dest("reverb_low_shelf_cutoff", "reverb", REVERB, 0.0, 0.2, 128.0)
mono_dest("reverb_low_shelf_gain", "reverb", REVERB, 0.0, -0.2, 6.0)
mono_dest("reverb_high_shelf_cutoff", "reverb", REVERB, 90.0, -0.2, 128.0)
mono_dest("reverb_high_shelf_gain", "reverb", REVERB, -1.0, -0.2, 6.0)
mono_dest("reverb_chorus_amount", "reverb", REVERB, 0.223607, 0.2, 1.0)
# stereo_routing acts on the master encoder: needs a stereo signal (unison).
mono_dest("stereo_routing", "chorus", [("chorus_on", 0)], 1.0, -0.3, 1.0, extra=STEREO)
# volume: the master's SquareRoot control, offset on the stored value
# (5473 - 0.5 * 0.2 * 7399.44 = 4733: -11.2 dB instead of -6 dB).
mono_dest("volume", "chorus", [("chorus_on", 0)], 5473.0404, -0.2, 7399.4404)
FILTER_FX = [("filter_fx_model", 3), ("filter_fx_cutoff", 60.0), ("filter_fx_resonance", 0.5)]
mono_dest("filter_fx_mix", "filter_fx", FILTER_FX, 1.0, -0.3, 1.0)
mono_dest("filter_fx_drive", "filter_fx", FILTER_FX, 0.0, 0.2, 20.0)
mono_dest("filter_fx_blend_transpose", "filter_fx",
          [("filter_fx_model", 6), ("filter_fx_cutoff", 60.0), ("filter_fx_resonance", 0.5),
           ("filter_fx_blend", 1.0)], 42.0, 0.1, 84.0)
FORMANT_FX = [("filter_fx_model", 5), ("filter_fx_cutoff", 60.0), ("filter_fx_resonance", 0.5)]
mono_dest("filter_fx_formant_x", "filter_fx", FORMANT_FX, 0.5, 0.2, 1.0)
mono_dest("filter_fx_formant_y", "filter_fx", FORMANT_FX, 0.5, -0.2, 1.0)
mono_dest("filter_fx_formant_transpose", "filter_fx", FORMANT_FX, 0.0, 0.2, 24.0)
mono_dest("filter_fx_formant_spread", "filter_fx", FORMANT_FX, 0.0, 0.2, 2.0)

# -- The remaining POLY destinations of the bank, and the routed ones no
#    case had verified (2026-09-13) ---------------------------------------
#
# Same method as the mono ones: a macro (a constant) into the destination
# and a static twin at the value it should produce. The macro is a mono
# source, so what these prove is the route, the scale (offsets on the
# STORED value for Quadratic / Quartic / Exponential controls) and the
# consumer; the per-voice regime is the poly route the cutoff cases prove.
# `extra` carries the settings the destination needs to be audible.
def poly_dest(destination, settings, base, amount, range_, note=45, extra_notes=()):
    macro = 0.5
    expected = base + macro * amount * range_
    common = [("macro_control_1", macro)] + list(settings)
    case("poly_macro_to_" + destination, "A macro into " + destination,
         common + [(destination, base)],
         modulations=[("macro_control_1", destination, amount)], note=note,
         extra_notes=extra_notes)
    case("poly_macro_to_" + destination + "_static",
         "The value the macro should give " + destination + ", set statically",
         common + [(destination, round(expected, 8))], note=note, extra_notes=extra_notes)

NO_FILTER = [("filter_1_on", 0)]
UNISON = [("osc_1_unison_voices", 4), ("osc_1_unison_detune", 3.0)]
# Voice pitch and glide. The primer is note 45 and the glide needs a
# different note to glide from, forced (no overlap between the notes).
poly_dest("voice_tune", NO_FILTER, 0.0, 0.2, 2.0)
poly_dest("voice_transpose", NO_FILTER, 0.0, 0.1, 96.0)
poly_dest("portamento_time", NO_FILTER + [("portamento_force", 1)], -3.0, 0.2, 14.0, note=52)
# Oscillator unison controls.
poly_dest("osc_1_detune_range", NO_FILTER + UNISON, 2.0, 0.1, 48.0)
poly_dest("osc_1_detune_power", NO_FILTER + UNISON, 1.5, 0.2, 10.0)
poly_dest("osc_1_unison_voices", NO_FILTER + [("osc_1_unison_detune", 3.0)], 2.0, 0.2, 15.0)
poly_dest("osc_1_unison_detune", NO_FILTER + [("osc_1_unison_voices", 4)], 3.0, 0.2, 10.0)
poly_dest("osc_1_unison_blend", NO_FILTER + UNISON, 0.8, -0.2, 1.0)
poly_dest("osc_1_stereo_spread", NO_FILTER + UNISON, 1.0, -0.3, 1.0)
poly_dest("osc_1_pan", NO_FILTER, 0.0, 0.2, 2.0)
poly_dest("osc_1_spectral_morph_amount", NO_FILTER + [("osc_1_spectral_morph_type", 7)], 0.3, 0.2, 1.0)
poly_dest("osc_1_spectral_morph_spread", NO_FILTER + UNISON + [("osc_1_spectral_morph_type", 7),
          ("osc_1_spectral_morph_amount", 0.3)], 0.0, 0.2, 1.0)
poly_dest("osc_1_distortion_amount", NO_FILTER + [("osc_1_distortion_type", 1)], 0.3, 0.2, 1.0)
poly_dest("osc_1_distortion_spread", NO_FILTER + UNISON + [("osc_1_distortion_type", 1),
          ("osc_1_distortion_amount", 0.3)], 0.0, 0.2, 1.0)
# Filter controls (digital model, and the formant model's four).
DIGITAL = [("filter_1_on", 1), ("filter_1_model", 3), ("filter_1_cutoff", 60.0),
           ("filter_1_resonance", 0.5)]
poly_dest("filter_1_resonance", DIGITAL[:3], 0.5, 0.2, 1.0)
poly_dest("filter_1_blend", DIGITAL, 0.0, 0.2, 2.0)
poly_dest("filter_1_mix", DIGITAL, 1.0, -0.3, 1.0)
poly_dest("filter_1_drive", DIGITAL, 0.0, 0.2, 20.0)
poly_dest("filter_1_keytrack", DIGITAL, 0.0, 0.2, 2.0, note=57)
FORMANT = [("filter_1_on", 1), ("filter_1_model", 5), ("filter_1_cutoff", 60.0),
           ("filter_1_resonance", 0.5)]
poly_dest("filter_1_formant_x", FORMANT, 0.5, 0.2, 1.0)
poly_dest("filter_1_formant_y", FORMANT, 0.5, -0.2, 1.0)
poly_dest("filter_1_formant_transpose", FORMANT, 0.0, 0.2, 24.0)
poly_dest("filter_1_formant_spread", FORMANT, 0.0, 0.2, 2.0)
# Envelope times and sustain, heard through env_2 -> cutoff.
ENV_TO_CUTOFF = DIGITAL + [("env_2_attack", 0.3), ("env_2_decay", 0.8), ("env_2_sustain", 0.5),
                           ("env_2_release", 0.5)]
def env_dest(name, base, amount, range_):
    macro = 0.5
    expected = base + macro * amount * range_
    settings = [s for s in ENV_TO_CUTOFF if s[0] != name] + [("macro_control_1", macro)]
    case("poly_macro_to_" + name, "A macro into " + name + ", heard on env_2 -> cutoff",
         settings + [(name, base)],
         modulations=[("env_2", "filter_1_cutoff", 0.3), ("macro_control_1", name, amount)])
    case("poly_macro_to_" + name + "_static", "The value the macro should give " + name,
         settings + [(name, round(expected, 8))],
         modulations=[("env_2", "filter_1_cutoff", 0.3)])
env_dest("env_2_attack", 0.3, 0.2, 2.37842)
env_dest("env_2_decay", 0.8, -0.2, 2.37842)
env_dest("env_2_sustain", 0.5, 0.2, 1.0)
env_dest("env_2_release", 0.5, 0.2, 2.37842)
# LFO controls, heard through lfo_1 -> cutoff (and random_1 -> cutoff).
LFO_TO_CUTOFF = DIGITAL + [("lfo_1_frequency", 2.0)]
def lfo_dest(name, settings, base, amount, range_, source="lfo_1", seed=None):
    macro = 0.5
    expected = base + macro * amount * range_
    common = settings + [("macro_control_1", macro)]
    case("poly_macro_to_" + name, "A macro into " + name + ", heard on " + source + " -> cutoff",
         common + [(name, base)],
         modulations=[(source, "filter_1_cutoff", 0.3), ("macro_control_1", name, amount)],
         random_seed=seed)
    case("poly_macro_to_" + name + "_static", "The value the macro should give " + name,
         common + [(name, round(expected, 8))],
         modulations=[(source, "filter_1_cutoff", 0.3)], random_seed=seed)
lfo_dest("lfo_1_frequency", DIGITAL, 2.0, 0.1, 16.0)
lfo_dest("lfo_1_tempo", DIGITAL + [("lfo_1_sync", 1)], 7.0, 0.5, 12.0)
lfo_dest("lfo_1_phase", LFO_TO_CUTOFF, 0.0, 0.5, 1.0)
lfo_dest("lfo_1_stereo", LFO_TO_CUTOFF, 0.0, 0.2, 1.0)
lfo_dest("lfo_1_delay_time", LFO_TO_CUTOFF, 0.0, 0.1, 4.0)
lfo_dest("lfo_1_fade_time", LFO_TO_CUTOFF, 0.0, 0.1, 8.0)
lfo_dest("lfo_1_smooth_time", LFO_TO_CUTOFF + [("lfo_1_smooth_mode", 1)], -7.5, 0.5, 14.0)
lfo_dest("random_1_frequency", DIGITAL, 2.0, 0.1, 16.0, source="random_1", seed=18)
lfo_dest("random_1_tempo", DIGITAL + [("random_1_sync", 1)], 7.0, 0.5, 12.0, source="random_1", seed=18)

# The keytracked LFO rate (sync index 4): the LFO runs at the frequency of
# bent midi + keytrack_transpose + keytrack_tune, the exact conversion.
# Transpose -36 puts an LFO at 110 Hz / 8 = 13.75 Hz on the cutoff; the
# tune shifts it by a semitone fraction. And the transpose as a
# destination, macro + static twin like the others.
case("mod_lfo_keytrack", "lfo_1 keytracked (sync 4, transpose -36) into the cutoff",
     DIGITAL + [("lfo_1_sync", 4), ("lfo_1_keytrack_transpose", -36.0)],
     modulations=[("lfo_1", "filter_1_cutoff", 0.3)])
case("mod_lfo_keytrack_tune", "The same with keytrack_tune 0.5",
     DIGITAL + [("lfo_1_sync", 4), ("lfo_1_keytrack_transpose", -36.0), ("lfo_1_keytrack_tune", 0.5)],
     modulations=[("lfo_1", "filter_1_cutoff", 0.3)])
lfo_dest("lfo_1_keytrack_transpose", DIGITAL + [("lfo_1_sync", 4)], -36.0, -0.1, 96.0)
case("mod_random_keytrack", "random_1 keytracked (sync 4, transpose -48) into the cutoff",
     DIGITAL + [("random_1_sync", 4), ("random_1_keytrack_transpose", -48.0)],
     modulations=[("random_1", "filter_1_cutoff", 0.3)], random_seed=18)

# The routed mono destinations no case had verified.
mono_dest("chorus_mod_depth", "chorus", CHORUS, 0.5, 0.2, 1.0)
mono_dest("chorus_feedback", "chorus", CHORUS, 0.4, 0.2, 1.9)
mono_dest("chorus_frequency", "chorus", CHORUS + [("chorus_sync", 0)], -3.0, 0.2, 9.0)
mono_dest("delay_feedback", "delay", DELAY, 0.5, -0.2, 2.0)
mono_dest("delay_dry_wet", "delay", DELAY, 0.5, -0.2, 1.0)
mono_dest("delay_frequency", "delay", DELAY + [("delay_sync", 0)], 2.0, 0.2, 11.0)
mono_dest("delay_aux_frequency", "delay", DELAY + [("delay_style", 1), ("delay_aux_sync", 0)], 2.0, 0.2, 11.0)
mono_dest("reverb_dry_wet", "reverb", REVERB, 0.5, -0.2, 1.0)
mono_dest("reverb_size", "reverb", REVERB, 0.5, 0.2, 1.0)
mono_dest("reverb_decay_time", "reverb", [("reverb_dry_wet", 0.5)], 0.0, -0.2, 12.0)
mono_dest("phaser_blend", "phaser", PHASER, 1.0, 0.2, 2.0)
mono_dest("phaser_feedback", "phaser", PHASER, 0.5, 0.2, 1.0)
mono_dest("phaser_dry_wet", "phaser", PHASER, 0.8, -0.3, 1.0)
mono_dest("flanger_dry_wet", "flanger", FLANGER, 0.4, -0.3, 0.5)
mono_dest("compressor_mix", "compressor", COMPRESSOR, 1.0, -0.3, 1.0)
mono_dest("compressor_high_gain", "compressor", COMPRESSOR, 16.3, -0.2, 60.0)
mono_dest("eq_band_cutoff", "eq", EQ, 80.0, -0.1, 128.0)
mono_dest("eq_band_gain", "eq", EQ, -6.0, 0.2, 30.0)
mono_dest("distortion_drive", "distortion", [("distortion_mix", 1.0)], 6.0, 0.2, 60.0)

# The rest of the bank's routed destinations, so every family in the
# table has a case (osc_N_wave_frame, sample_* and volume excepted: the
# bench loads a single-cycle table, no sample, and the master volume is
# not a modulation destination here).
mono_dest("chorus_dry_wet", "chorus", [], 0.5, -0.2, 1.0)
mono_dest("phaser_mod_depth", "phaser", PHASER, 24.0, 0.2, 48.0)
mono_dest("filter_fx_blend", "filter_fx", FILTER_FX, 0.0, 0.2, 2.0)
mono_dest("filter_fx_resonance", "filter_fx", FILTER_FX[:2], 0.5, 0.2, 1.0)
mono_dest("eq_low_gain", "eq", EQ[1:], 8.0, -0.2, 30.0)
mono_dest("eq_high_gain", "eq", EQ[:2], -8.0, 0.2, 30.0)
mono_dest("eq_high_cutoff", "eq", EQ, 100.0, -0.1, 128.0)
mono_dest("compressor_low_gain", "compressor", COMPRESSOR, 0.0, 0.2, 60.0)
mono_dest("compressor_band_gain", "compressor", COMPRESSOR, 0.0, 0.2, 60.0)
poly_dest("filter_1_blend_transpose", [("filter_1_on", 1), ("filter_1_model", 6), ("filter_1_cutoff", 60.0),
          ("filter_1_resonance", 0.5), ("filter_1_blend", 1.0)], 42.0, 0.1, 84.0)
poly_dest("osc_1_distortion_phase", NO_FILTER + [("osc_1_distortion_type", 1), ("osc_1_distortion_amount", 0.4)], 0.5, 0.2, 1.0)
poly_dest("osc_1_frame_spread", NO_FILTER + UNISON, 0.0, 0.1, 256.0)
env_dest("env_2_delay", 0.0, 0.2, 2.37842)
env_dest("env_2_hold", 0.0, 0.2, 2.37842)

# -- A macro as a destination (10 connections in the bank) ----------------
#
# `macro_control_N` is a mono mod control in the reference's voice
# handler: modulated like any control, then read as a source. Three
# cases: a constant into it (route and scale, static twin), a stepping
# poly source into it (when does the connection reading the macro see
# the step: the twins bracket it, per-block RMS says the lag), and an
# LFO into it (the regime, judged against Spinwave directly).
MACRO_CHAIN = DIGITAL + [("macro_control_1", 0.6), ("macro_control_2", 0.2)]
case("macro_dest_constant", "macro_1 into macro_2, macro_2 into the cutoff",
     MACRO_CHAIN,
     modulations=[("macro_control_2", "filter_1_cutoff", 0.3),
                  ("macro_control_1", "macro_control_2", 0.5)])
case("macro_dest_constant_static", "macro_2 at the value macro_1 should give it (0.2 + 0.6 * 0.5 = 0.5)",
     DIGITAL + [("macro_control_1", 0.6), ("macro_control_2", 0.5)],
     modulations=[("macro_control_2", "filter_1_cutoff", 0.3)])
STEP = DIGITAL + [("macro_control_2", 0.2),
                  ("env_2_attack", 0.0), ("env_2_decay", 1.0), ("env_2_sustain", 1.0)]
case("macro_dest_step", "env_2 (attack 0) stepping macro_2, macro_2 into the cutoff",
     STEP,
     modulations=[("macro_control_2", "filter_1_cutoff", 0.3),
                  ("env_2", "macro_control_2", 0.3)])
case("macro_dest_step_twin_high", "macro_2 at the stepped value (0.2 + 0.3 = 0.5), static",
     DIGITAL + [("macro_control_2", 0.5)],
     modulations=[("macro_control_2", "filter_1_cutoff", 0.3)])
case("macro_dest_step_twin_low", "macro_2 unstepped, static",
     DIGITAL + [("macro_control_2", 0.2)],
     modulations=[("macro_control_2", "filter_1_cutoff", 0.3)])
case("macro_dest_lfo", "lfo_1 (8 Hz) into macro_2, macro_2 into the cutoff",
     DIGITAL + [("macro_control_2", 0.2), ("lfo_1_frequency", 3.0)],
     modulations=[("macro_control_2", "filter_1_cutoff", 0.3),
                  ("lfo_1", "macro_control_2", 0.3)])

# -- Meta-modulation: a connection's amount as a destination ----------------
#
# Half of the real presets' refused connections go into
# `modulation_N_amount`. Each behaviour below is settled by a case (and
# its twin, differing by one setting) BEFORE anything is ported: the
# reference's bytes answer, not a reading of its code.
FILTER = [("filter_1_on", 1), ("filter_1_model", 3),
          ("filter_1_cutoff", 55.0), ("filter_1_resonance", 0.4)]
# Every value of a case stays INTERIOR to its range over the measured
# window (rule of 2026-09-12, checked automatically by
# spinwave-control/src/bounds.rs on every render): a value against a
# bound measures the clamp, not the connection. The cutoff's range is
# [8, 136] and a connection into it scales by 128, so from 55 the summed
# amount of everything reaching the cutoff stays below 0.63 (unipolar)
# or ±0.36 (bipolar). The bounds cases are the deliberate exception and
# say so in golden.rs.

# 1. Minimal: a macro on the amount of LFO -> cutoff. The twin has no
#    meta connection: if the two references are identical, the meta
#    connection never arrived.
case("meta_macro_to_amount", "A macro modulating the amount of lfo_1 -> cutoff",
     FILTER + [("lfo_1_frequency", 2.0), ("macro_control_1", 0.6)],
     modulations=[("lfo_1", "filter_1_cutoff", 0.1),
                  ("macro_control_1", "modulation_1_amount", 0.3)])
case("meta_macro_to_amount_twin", "The same without the meta connection",
     FILTER + [("lfo_1_frequency", 2.0), ("macro_control_1", 0.6)],
     modulations=[("lfo_1", "filter_1_cutoff", 0.1)])
# ...and the static amount the meta connection is expected to produce
# (0.1 + 0.6 * 0.3 * range 2 = 0.46), to read the scale off the bytes.
case("meta_macro_to_amount_static", "The amount the meta connection should give, set statically",
     FILTER + [("lfo_1_frequency", 2.0), ("macro_control_1", 0.6)],
     modulations=[("lfo_1", "filter_1_cutoff", 0.46)])

# 2. Chaining, in the two slot orders. Same graph: macro -> amount of
#    (env_2 -> amount of (lfo_1 -> cutoff)). If the two references are
#    identical, slot order does not matter; if not, it does, and the
#    difference says how (a block of lag on the later slot, presumably).
#    Amounts kept small (each link multiplies by the amount range, 2) so
#    nothing clamps: 0.1 + env * (0.05 + 0.8 * 0.05 * 2) * 2 = 0.36 at
#    most, cutoff 101. A first version with 0.5s saturated at 1 and hid
#    the chain; a second with 0.1s reached cutoff 134.
case("meta_chain_forward", "A chain of amounts, sources in slot order",
     FILTER + [("lfo_1_frequency", 2.0), ("macro_control_1", 0.8),
               ("env_2_attack", 0.3), ("env_2_sustain", 1.0)],
     modulations=[("lfo_1", "filter_1_cutoff", 0.1),
                  ("env_2", "modulation_1_amount", 0.05),
                  ("macro_control_1", "modulation_2_amount", 0.05)])
case("meta_chain_backward", "The same chain, slots reversed",
     FILTER + [("lfo_1_frequency", 2.0), ("macro_control_1", 0.8),
               ("env_2_attack", 0.3), ("env_2_sustain", 1.0)],
     modulations=[("macro_control_1", "modulation_2_amount", 0.05),
                  ("env_2", "modulation_3_amount", 0.05),
                  ("lfo_1", "filter_1_cutoff", 0.1)])

# The chain without its last link, twin of both orders above (the macro
# must be seen to arrive) and of the cycle below (slot 3 must be seen to
# act).
case("meta_chain_no_macro", "The chain without the macro link",
     FILTER + [("lfo_1_frequency", 2.0), ("macro_control_1", 0.8),
               ("env_2_attack", 0.3), ("env_2_sustain", 1.0)],
     modulations=[("lfo_1", "filter_1_cutoff", 0.1),
                  ("env_2", "modulation_1_amount", 0.05)])

# 3. NOT a cycle, though first named one: env_2 on the LFO connection's
#    amount, lfo_1 on the env connection's amount — the meta sources are
#    the raw LFO and envelope, so the processor graph is a three-link
#    chain in a different shape. Kept: it is what found that an
#    audio-rate source's control value is its buffer's first sample.
case("meta_chain_three_links", "lfo_1 and env_2 each on the other's connection amount",
     FILTER + [("lfo_1_frequency", 2.0),
               ("env_2_attack", 0.3), ("env_2_sustain", 1.0)],
     modulations=[("lfo_1", "filter_1_cutoff", 0.1),
                  ("env_2", "modulation_1_amount", 0.05),
                  ("lfo_1", "modulation_2_amount", 0.05)])

# 3b. A TRUE cycle in the processor graph: connection X (slot 1, lfo_1
#     -> amount of slot 2) and connection Y (slot 2, env_2 -> amount of
#     slot 1) each modulate the other's amount; slot 3 carries the result
#     to the cutoff (macro -> cutoff, its amount modulated by... nothing:
#     it just plays). To hear the cycle, X's output must reach audio: so
#     X targets slot 3's amount as well? A connection has one destination.
#     Instead: X = lfo_1 -> amount of Y; Y = env_2 -> amount of X; and Z =
#     lfo_1 -> cutoff whose amount is modulated by Y (Y has one
#     destination too)... The reachable design: Y = env_2 -> amount of X,
#     X = lfo_1 -> amount of Y's own slot is impossible with one
#     destination each. So the cycle is closed through the amounts
#     directly: X (slot 1) = lfo_1 -> modulation_2_amount, Y (slot 2) =
#     env_2 -> modulation_1_amount. Neither reaches audio; the cutoff
#     twin Z (slot 3) = lfo_2 -> filter_1_cutoff with lfo_2 slow is only
#     there so the render is not silent, and the cycle's effect is
#     invisible in it. What this case establishes is only that the
#     reference renders it (no hang, no NaN) — and that ours does.
#     It rests on the clamp by nature: the loop gain of a two-cycle is
#     4 × source_1 × source_2 (each link scales by the amount range),
#     above 1 for any two sources past 0.5, so the amounts saturate at 1
#     whatever the base amounts. Allowed in golden.rs for that reason.
case("meta_true_cycle", "Two meta connections modulating each other's amounts",
     FILTER + [("lfo_1_frequency", 2.0), ("lfo_2_frequency", 0.0),
               ("env_2_attack", 0.3), ("env_2_sustain", 1.0)],
     modulations=[("lfo_1", "modulation_2_amount", 0.3),
                  ("env_2", "modulation_1_amount", 0.3),
                  ("lfo_2", "filter_1_cutoff", 0.3)])
# ...and the audible version: the cycle's slot 1 also drives the cutoff
# through a third connection whose amount slot 1 modulates? Not
# expressible. The audible cycle needs a connection with two effects,
# which the matrix does not have; a generated patch cannot make one
# either. Bounded, deterministic, not NaN is the requirement, and that
# is testable on the silent-effect case above.

# 4. Timing: an envelope with no attack steps the amount of a constant
#    connection at note-on. Two static twins bracket it: if the
#    reference matches "amount already stepped" from the first block,
#    the modulated amount is read in the block it changes; the first
#    differing sample against each twin says which.
case("meta_step_timing", "env_2 (attack 0) stepping the amount of macro -> cutoff",
     FILTER + [("macro_control_1", 1.0),
               ("env_2_attack", 0.0), ("env_2_decay", 1.0), ("env_2_sustain", 1.0)],
     modulations=[("macro_control_1", "filter_1_cutoff", 0.1),
                  ("env_2", "modulation_1_amount", 0.2)])
case("meta_step_timing_twin_high", "The stepped amount, static (0.1 + 1 * 0.2 * 2 = 0.5)",
     FILTER + [("macro_control_1", 1.0)],
     modulations=[("macro_control_1", "filter_1_cutoff", 0.5)])
case("meta_step_timing_twin_low", "The unstepped amount, static",
     FILTER + [("macro_control_1", 1.0)],
     modulations=[("macro_control_1", "filter_1_cutoff", 0.1)])

# 4b. The lag is a property of the TARGET's source, not of the meta
#     source: the port found that a target fed by a mono source (a macro)
#     reads its meta-modulated amount one block late, and a target fed
#     by a poly source (an LFO) reads it in the block. The rule was found
#     on meta_step_timing alone; these two cross it. A slow envelope on
#     the amount of macro -> cutoff (lag on a 300 ms ramp = ~1 %, visible),
#     and a zero-attack envelope on the amount of lfo_1 -> cutoff (a step:
#     lag or not is one block of difference).
case("meta_ramp_on_mono_source_target", "env_2 (attack 0.3 s) on the amount of macro -> cutoff",
     FILTER + [("macro_control_1", 1.0),
               ("env_2_attack", 0.3), ("env_2_sustain", 1.0)],
     modulations=[("macro_control_1", "filter_1_cutoff", 0.1),
                  ("env_2", "modulation_1_amount", 0.2)])
case("meta_step_on_poly_source_target", "env_2 (attack 0) on the amount of lfo_1 -> cutoff",
     FILTER + [("lfo_1_frequency", 2.0),
               ("env_2_attack", 0.0), ("env_2_decay", 1.0), ("env_2_sustain", 1.0)],
     modulations=[("lfo_1", "filter_1_cutoff", 0.1),
                  ("env_2", "modulation_1_amount", 0.2)])

# 5. Bounds: a meta connection pushing the amount to 0.5 + 1.0 * 1.0 * 2
#    = 2.5. Twins at 1.0 (clamped) and 2.5 (overflowed), set statically.
case("meta_bounds", "A meta connection pushing an amount past 1",
     FILTER + [("lfo_1_frequency", 2.0), ("macro_control_1", 1.0)],
     modulations=[("lfo_1", "filter_1_cutoff", 0.5),
                  ("macro_control_1", "modulation_1_amount", 1.0)])
case("meta_bounds_twin_clamped", "The amount clamped to 1, static",
     FILTER + [("lfo_1_frequency", 2.0), ("macro_control_1", 1.0)],
     modulations=[("lfo_1", "filter_1_cutoff", 1.0)])
case("meta_bounds_twin_overflow", "The amount at 2.5, static",
     FILTER + [("lfo_1_frequency", 2.0), ("macro_control_1", 1.0)],
     modulations=[("lfo_1", "filter_1_cutoff", 2.5)])

# 7. Power, which is NOT the amount: range [-10, 10], so a meta
#    connection into it scales by 20. A macro at 0.5 with amount 0.2 adds
#    +2; the twin sets power 2 statically. And bounds: macro 1.0, amount
#    1.0 adds +20; twins at 10 (clamped) and 20 (overflowed).
case("meta_power", "A macro modulating the power of lfo_1 -> cutoff",
     FILTER + [("lfo_1_frequency", 2.0), ("macro_control_1", 0.5)],
     modulations=[("lfo_1", "filter_1_cutoff", 0.5),
                  ("macro_control_1", "modulation_1_power", 0.2)])
case("meta_power_static", "The power the meta connection should give, set statically",
     FILTER + [("lfo_1_frequency", 2.0), ("macro_control_1", 0.5)],
     modulations=[("lfo_1", "filter_1_cutoff", 0.5, {"power": 2.0})])
case("meta_power_bounds", "A meta connection pushing the power to 20",
     FILTER + [("lfo_1_frequency", 2.0), ("macro_control_1", 1.0)],
     modulations=[("lfo_1", "filter_1_cutoff", 0.5),
                  ("macro_control_1", "modulation_1_power", 1.0)])
case("meta_power_bounds_twin_clamped", "Power 10, static",
     FILTER + [("lfo_1_frequency", 2.0), ("macro_control_1", 1.0)],
     modulations=[("lfo_1", "filter_1_cutoff", 0.5, {"power": 10.0})])
case("meta_power_bounds_twin_overflow", "Power 20, static",
     FILTER + [("lfo_1_frequency", 2.0), ("macro_control_1", 1.0)],
     modulations=[("lfo_1", "filter_1_cutoff", 0.5, {"power": 20.0})])

# 8. The target connection is BIPOLAR: does the modulated amount enter
#    before or after the polarity branch? If after (a multiplier on
#    (value - 0.5)), the static twin with amount 0.4 and bipolar matches
#    (0.1 + 0.6 * 0.25 * 2; the first version at 0.9 swung the cutoff to
#    -2.6).
case("meta_on_bipolar_target", "A macro on the amount of a bipolar lfo_1 -> cutoff",
     FILTER + [("lfo_1_frequency", 2.0), ("macro_control_1", 0.6)],
     modulations=[("lfo_1", "filter_1_cutoff", 0.1, {"bipolar": 1}),
                  ("macro_control_1", "modulation_1_amount", 0.25)])
case("meta_on_bipolar_target_static", "Bipolar lfo_1 -> cutoff at amount 0.4, static",
     FILTER + [("lfo_1_frequency", 2.0), ("macro_control_1", 0.6)],
     modulations=[("lfo_1", "filter_1_cutoff", 0.4, {"bipolar": 1})])

# 9. The META connection is driven by an LFO (created bipolar by the
#    reference unless told otherwise — told otherwise here, and told
#    bipolar in the twin). lfo_2 slow on the amount of lfo_1 -> cutoff.
case("meta_lfo_source_unipolar", "lfo_2 (unipolar) on the amount of lfo_1 -> cutoff",
     FILTER + [("lfo_1_frequency", 2.0), ("lfo_2_frequency", 0.0)],
     modulations=[("lfo_1", "filter_1_cutoff", 0.2),
                  ("lfo_2", "modulation_1_amount", 0.15, {"bipolar": 0})])
case("meta_lfo_source_bipolar", "lfo_2 (bipolar) on the amount of lfo_1 -> cutoff",
     FILTER + [("lfo_1_frequency", 2.0), ("lfo_2_frequency", 0.0)],
     modulations=[("lfo_1", "filter_1_cutoff", 0.2),
                  ("lfo_2", "modulation_1_amount", 0.15, {"bipolar": 1})])

# 10. A POLY meta source with two voices: velocity on the amount of
#     lfo_1 -> cutoff, two notes of different velocities sounding
#     together. If the amount is resolved per voice, the two voices get
#     different LFO depths; if it were one value, the same.
case("meta_poly_source_two_voices", "velocity on the amount of lfo_1 -> cutoff, two voices",
     FILTER + [("lfo_1_frequency", 2.0)],
     modulations=[("lfo_1", "filter_1_cutoff", 0.2),
                  ("velocity", "modulation_1_amount", 0.15)],
     extra_notes=[(52, 0.3, 1.15, 0.5)])

# 11. The target connection is BYPASSED while a meta connection feeds
#     its amount: the twin has no connections at all. Identical bytes =
#     bypass wins over the modulated amount.
case("meta_bypassed_target", "A macro on the amount of a bypassed lfo_1 -> cutoff",
     FILTER + [("lfo_1_frequency", 2.0), ("macro_control_1", 0.6)],
     modulations=[("lfo_1", "filter_1_cutoff", 0.3, {"bypass": 1}),
                  ("macro_control_1", "modulation_1_amount", 0.5)])
case("meta_bypassed_target_twin", "No connection at all",
     FILTER + [("lfo_1_frequency", 2.0), ("macro_control_1", 0.6)])

# 6. Regime: a fast LFO on the amount of an AUDIO-RATE connection (an
#    envelope into the cutoff). Per block or per sample is what the port
#    will have to match; the reference's bytes are the target either way.
case("meta_lfo_on_audio_rate_amount", "lfo_1 (8 Hz) on the amount of env_2 -> cutoff",
     FILTER + [("lfo_1_frequency", 3.0),
               ("env_2_attack", 0.05), ("env_2_decay", 0.6), ("env_2_sustain", 0.3)],
     modulations=[("env_2", "filter_1_cutoff", 0.25),
                  ("lfo_1", "modulation_1_amount", 0.1)])

# Envelope shapes: the quartic time scaling and the sustain law.
case("env_fast", "A short percussive envelope",
     [("filter_1_on", 0),
      ("env_1_attack", 0.0), ("env_1_decay", 0.35),
      ("env_1_sustain", 0.0), ("env_1_release", 0.2)])
case("env_slow", "A slow pad envelope",
     [("filter_1_on", 0),
      ("env_1_attack", 0.5), ("env_1_decay", 0.7),
      ("env_1_sustain", 0.8), ("env_1_release", 0.6)])

# The modulation matrix, which is where this week's worst bug lived: the
# LFO and random sources were squashed into the top half of their range,
# halving every modulation depth, and no test noticed. A connection is not
# a control on either side, so both harnesses wire these through their own
# path and the `modulate` directive drives both.

# An LFO on the filter cutoff: the plainest control-rate path.
case("mod_lfo_to_cutoff", "LFO 1 to filter cutoff, the plain control-rate path",
     [("filter_1_on", 1), ("filter_1_model", 3),
      ("filter_1_cutoff", 60.0), ("filter_1_resonance", 0.4),
      ("lfo_1_frequency", 2.0)],
     modulations=[("lfo_1", "filter_1_cutoff", 0.4)])

# Bipolar, which takes the other branch of the transform. The four LFO
# -> cutoff cases share one amount, 0.4: at 0.7 the unipolar ones
# reached cutoff 150 and 170 (range [8, 136]).
case("mod_lfo_bipolar", "The same LFO, bipolar",
     [("filter_1_on", 1), ("filter_1_model", 3),
      ("filter_1_cutoff", 80.0), ("filter_1_resonance", 0.4),
      ("lfo_1_frequency", 2.0)],
     modulations=[("lfo_1", "filter_1_cutoff", 0.4, {"bipolar": 1})])

# The bipolar case passes and the unipolar one fails, on the same source
# and the same destination. Two things differ, not one: the polarity AND
# the base cutoff (80 against 60). These two split them. If the unipolar
# case passes at 80 the polarity is innocent and the base value decides
# how much a cutoff error is worth; if it still fails, polarity is real.
case("mod_lfo_to_cutoff_high", "The unipolar LFO at the bipolar case's base cutoff",
     [("filter_1_on", 1), ("filter_1_model", 3),
      ("filter_1_cutoff", 80.0), ("filter_1_resonance", 0.4),
      ("lfo_1_frequency", 2.0)],
     modulations=[("lfo_1", "filter_1_cutoff", 0.4)])

case("mod_lfo_bipolar_low", "The bipolar LFO at the unipolar case's base cutoff",
     [("filter_1_on", 1), ("filter_1_model", 3),
      ("filter_1_cutoff", 60.0), ("filter_1_resonance", 0.4),
      ("lfo_1_frequency", 2.0)],
     modulations=[("lfo_1", "filter_1_cutoff", 0.4, {"bipolar": 1})])

# The same unipolar LFO into a destination the kernel does NOT consume
# per sample. Filter cutoff is the one audio-rate destination, so
# lfo -> cutoff is evaluated sample by sample while lfo -> level is
# evaluated once per block. If this passes, the fault is confined to the
# audio-rate path; if it fails too, it is the transform or the source and
# the path is innocent.
# Level 0.7 + 0.2: at 0.7 the sum reached 1.4 and measured the clamp.
case("mod_lfo_to_level", "The unipolar LFO into a control-rate destination",
     [("filter_1_on", 0)],
     modulations=[("lfo_1", "osc_1_level", 0.2)])

# An envelope on pitch: a per-voice destination rather than the filter.
case("mod_env_to_pitch", "Envelope 2 to oscillator pitch",
     [("filter_1_on", 0),
      ("env_2_attack", 0.0), ("env_2_decay", 0.4),
      ("env_2_sustain", 0.3), ("env_2_release", 0.3)],
     modulations=[("env_2", "osc_1_transpose", 0.5)])

# The three other oscillator inputs the reference evaluates per sample
# (`createPolyModControl(..., audio_rate = true)` in OscillatorModule):
# tune, phase, and transpose again but snapped. mod_env_to_pitch failed
# for as long as transpose was ramped once per block; these pin the same
# fix on the inputs that share its code path but have no case of their
# own. The snapped one exercises the per-sample snap: the reference snaps
# (ramped note, ramped transpose + envelope) at every sample, which is not
# the same as snapping once and ramping the result.
case("mod_env_to_tune", "Envelope 2 to oscillator tune",
     [("filter_1_on", 0),
      ("env_2_attack", 0.0), ("env_2_decay", 0.4),
      ("env_2_sustain", 0.3), ("env_2_release", 0.3)],
     modulations=[("env_2", "osc_1_tune", 0.4)])

# Phase from 0.25 (the preamble's 0 would put the LFO's trough on the
# bound), and the tune above at 0.4 (0.6 reached 1.2 in [-1, 1] and
# measured the clamp exit, not the tune).
case("mod_lfo_to_phase", "The LFO into the oscillator's manual phase",
     [("filter_1_on", 0), ("lfo_1_frequency", 2.0), ("osc_1_phase", 0.25)],
     modulations=[("lfo_1", "osc_1_phase", 0.5)])

# 145 = bits 0, 4, 7: a major triad; the decaying transpose sweep lands
# on chord tones only.
case("mod_env_to_pitch_snapped", "Envelope 2 to a snapped oscillator transpose",
     [("filter_1_on", 0), ("osc_1_transpose_quantize", 145),
      ("env_2_attack", 0.0), ("env_2_decay", 0.5),
      ("env_2_sustain", 0.3), ("env_2_release", 0.3)],
     modulations=[("env_2", "osc_1_transpose", 0.5)])

# An envelope on level: the amplitude path, where the squashing bug bit.
case("mod_env_to_level", "Envelope 2 to oscillator level",
     [("filter_1_on", 0),
      ("env_2_attack", 0.1), ("env_2_decay", 0.5),
      ("env_2_sustain", 0.4), ("env_2_release", 0.3)],
     modulations=[("env_2", "osc_1_level", 0.2)])

# Two sources stacked on one destination: the matrix has to sum them.
case("mod_two_sources_one_dest", "An LFO and an envelope on the same cutoff",
     [("filter_1_on", 1), ("filter_1_model", 3),
      ("filter_1_cutoff", 55.0), ("filter_1_resonance", 0.4),
      ("lfo_1_frequency", 3.0),
      ("env_2_attack", 0.0), ("env_2_decay", 0.5), ("env_2_sustain", 0.2)],
     modulations=[("lfo_1", "filter_1_cutoff", 0.4),
                  ("env_2", "filter_1_cutoff", 0.5)])

# A source that does not move. Every other modulation case changes at the
# note onset from both ends at once: the source starts (an envelope from
# zero, an LFO from its retrigger phase, a random value drawn fresh) and
# the destination begins receiving modulation. That confounds the two, and
# it is why the divergence in those cases could not be pinned on either.
# A macro sits at a fixed value from before the first note until after the
# last, so an onset ramp seen HERE belongs to the destination path and
# nothing else; the absence of one puts the blame on the sources.
case("mod_macro_to_cutoff", "Macro 1, a source that never moves, to filter cutoff",
     [("filter_1_on", 1), ("filter_1_model", 3),
      ("filter_1_cutoff", 55.0), ("filter_1_resonance", 0.4),
      ("macro_control_1", 0.75)],
     modulations=[("macro_control_1", "filter_1_cutoff", 0.7)])

# A source that is POLY but does not move, which is the case that splits
# the two things `mod_macro_to_cutoff` proves at once. A macro differs
# from the failing cases twice over: it is mono rather than poly, AND
# constant rather than varying. Velocity is per-voice like an LFO and
# fixed for the life of the note like a macro, so it isolates the route
# from the dynamics. If this FAILS the poly route is at fault whatever the
# source does; if it PASSES the fault is in what varies over time, and the
# one-block lead the probe found becomes the suspect again.
case("mod_velocity_to_cutoff", "Velocity: a poly source that never moves, to cutoff",
     [("filter_1_on", 1), ("filter_1_model", 3),
      ("filter_1_cutoff", 55.0), ("filter_1_resonance", 0.4)],
     modulations=[("velocity", "filter_1_cutoff", 0.7)])

# The same question asked of key tracking, which is poly, constant, and
# reaches the voice by a different route than velocity does.
case("mod_note_to_cutoff", "Note (key tracking), the other poly constant, to cutoff",
     [("filter_1_on", 1), ("filter_1_model", 3),
      ("filter_1_cutoff", 55.0), ("filter_1_resonance", 0.4)],
     modulations=[("note", "filter_1_cutoff", 0.7)])

# Two notes at once, so the second occupies the OTHER lane of the voice
# pair. A fold across voice lanes that is counted twice or dropped shows
# up here and not on a single note, because with one voice the wrong fold
# and the right one agree.
case("mod_two_voices_one_lfo", "An LFO to cutoff with two voices sounding together",
     [("filter_1_on", 1), ("filter_1_model", 3),
      ("filter_1_cutoff", 55.0), ("filter_1_resonance", 0.4),
      ("lfo_1_frequency", 2.0)],
     modulations=[("lfo_1", "filter_1_cutoff", 0.4)],
     extra_notes=[(52, 0.8, 1.15, 0.5)])

# The random source, whose values are drawn per note (Perlin style: a
# gradient-noise hump between two draws, at 2 Hz here). Without the seed
# the two sides draw from different generators and compare noise: the
# reference's random_1 holds seed 18 (the 19th generator its process
# builds), Spinwave's held 684. random_seed.py fitted both from the
# probe curves — residual 1e-9 — and the second note used draws 5 and 7
# (slot 1 of the same generator) on both sides. Only the seed differed.
case("mod_random_to_cutoff", "Random 1 to filter cutoff",
     [("filter_1_on", 1), ("filter_1_model", 3),
      ("filter_1_cutoff", 65.0), ("filter_1_resonance", 0.4),
      ("random_1_frequency", 1.0)],
     modulations=[("random_1", "filter_1_cutoff", 0.6)],
     random_seed=18)


# Pitch: a note two octaves up exercises the band-limiting hardest, where
# a mip-selection difference would show.
case("osc_high_note", "The same saw two octaves up, hardest on band-limiting",
     [("filter_1_on", 0)], note=69)


# The other random generators, and the other voices. The reference seeds
# every RandomGenerator from a process counter in construction order:
# TriggerRandom, then random_1..4 (synth_voice_handler.cpp), so random_N
# of the first voice pair should hold seed 18 + (N - 1) — Spinwave's
# `reseed` gives kernel 0's random_N the case seed + (N - 1) — and a
# second voice pair (a clone of the router) holds whatever the clone's
# copy-constructions drew. The bank's random-driven presets (A Night in
# Kalyan, Special Glitch Thing: random_2) diverged; these say whether the
# seed model or the LFO is at fault.
for n in (2, 3, 4):
    case("mod_random_{}_to_cutoff".format(n), "Random {} to filter cutoff".format(n),
         [("filter_1_on", 1), ("filter_1_model", 3),
          ("filter_1_cutoff", 65.0), ("filter_1_resonance", 0.4),
          ("random_{}_frequency".format(n), 1.0)],
         modulations=[("random_{}".format(n), "filter_1_cutoff", 0.6)],
         random_seed=18)
case("mod_random_to_cutoff_two_voices", "Random 1 to filter cutoff, a second voice sounding",
     [("filter_1_on", 1), ("filter_1_model", 3),
      ("filter_1_cutoff", 65.0), ("filter_1_resonance", 0.4),
      ("random_1_frequency", 1.0)],
     modulations=[("random_1", "filter_1_cutoff", 0.6)],
     random_seed=18, extra_notes=[(52, 0.9, 1.15, 0.5)])
# The per-note `random` source (TriggerRandom, one draw in [0, 1) per
# note-on): seed 17 by the same counter.
case("mod_note_random_to_cutoff", "The per-note random source to filter cutoff",
     [("filter_1_on", 1), ("filter_1_model", 3),
      ("filter_1_cutoff", 65.0), ("filter_1_resonance", 0.4)],
     modulations=[("random", "filter_1_cutoff", 0.6)],
     random_seed=18)


# The reference's RandomLfo is an audio-rate processor whatever it feeds
# (`RandomLfoModule` never sets it control rate): Perlin and sine ramp
# from `last_value_` across the block, sample-and-hold steps AT the wrap
# sample, Lorenz runs per sample, and a control-rate consumer reads the
# buffer's first sample. Spinwave rendered every style as one value per
# block ramped by the destination — the same thing for Perlin between
# resets, not on a reset block, not for the other styles (the bank has
# 14 presets on sample-and-hold). These say what each style costs.
RANDOM_FILTER = [("filter_1_on", 1), ("filter_1_model", 3),
                 ("filter_1_cutoff", 65.0), ("filter_1_resonance", 0.4)]
for style, name in ((1, "sample_hold"), (2, "sin"), (3, "lorenz")):
    case("mod_random_{}_to_cutoff".format(name), "Random 1 ({}) to filter cutoff".format(name),
         RANDOM_FILTER + [("random_1_frequency", 3.0), ("random_1_style", style)],
         modulations=[("random_1", "filter_1_cutoff", 0.6)], random_seed=18)
    case("mod_random_{}_to_cutoff_two_voices".format(name),
         "Random 1 ({}) to filter cutoff, a second voice sounding".format(name),
         RANDOM_FILTER + [("random_1_frequency", 3.0), ("random_1_style", style)],
         modulations=[("random_1", "filter_1_cutoff", 0.6)], random_seed=18,
         extra_notes=[(52, 0.9, 1.15, 0.5)])
# ... and a control-rate destination: the resonance, read once per block.
for style, name in ((0, "perlin"), (1, "sample_hold")):
    case("mod_random_{}_to_resonance".format(name), "Random 1 ({}) to filter resonance".format(name),
         RANDOM_FILTER + [("filter_1_cutoff", 80.0), ("random_1_frequency", 3.0), ("random_1_style", style)],
         modulations=[("random_1", "filter_1_resonance", 0.5)], random_seed=18)
# Sync type 1 ("sync"): one shared state for every voice, phased from the
# transport, no reset on note-on (`doReset` returns when kSync is set).
# NEITHER harness runs a transport (no `correctToTime` in main.cpp, the
# session's transport stopped), so both sides measure the source at 0
# for the whole render (probed 2026-09-13): these pin the stopped-
# transport behaviour only. The shared curve under a running transport
# is UNMEASURED (notes/bank-compare.md).
for style, name in ((0, "perlin"), (1, "sample_hold")):
    case("mod_random_{}_sync_two_voices".format(name),
         "Random 1 ({}, sync type 1) to filter cutoff, two voices".format(name),
         RANDOM_FILTER + [("random_1_frequency", 3.0), ("random_1_style", style),
                          ("random_1_sync_type", 1)],
         modulations=[("random_1", "filter_1_cutoff", 0.6)], random_seed=18,
         extra_notes=[(52, 0.9, 1.15, 0.5)])

# The `stereo` source: `cr::Value(constants::kLeftOne)` = 1 on the left
# lane, 0 on the right, so a unipolar connection moves the left channel
# only (the bank's DIY, Salomon, Metal Head, Destruction... 41
# connections). Spinwave held [0, 1] until measured (2026-09-13).
case("mod_stereo_to_cutoff", "The stereo source to filter cutoff: the left channel moves",
     RANDOM_FILTER, modulations=[("stereo", "filter_1_cutoff", 0.4)])
case("mod_stereo_to_osc_level", "The stereo source to osc 1 level: the left channel louder",
     [("filter_1_on", 0), ("osc_1_level", 0.4)],
     modulations=[("stereo", "osc_1_level", 0.4)])

# Control-rate sources into the (audio-rate) oscillator level: the
# bank's Strings Section (velocity -> osc_2_level) and Banana Wob
# (macro_1 -> osc_1_level) diverged with nothing else to blame.
poly_dest("osc_1_level", NO_FILTER, 0.4, 0.4, 1.0)
case("mod_velocity_to_osc_level", "Velocity into osc 1 level",
     NO_FILTER + [("osc_1_level", 0.4)],
     modulations=[("velocity", "osc_1_level", 0.4)])

# Strings Section (7.4 dB, 2026-09-13) bisected to osc_2, FM'd by osc_1
# (distortion type 7), whose level is 0 with velocity on it: the carrier
# only sounds through the modulation. The twin sets the level the
# velocity (0.9 * 0.5) should give.
OSC2_FM = [("filter_1_on", 0), ("osc_1_level", 0.4),
           ("osc_2_on", 1), ("osc_2_random_phase", 0), ("osc_2_phase", 0),
           ("osc_2_distortion_type", 7), ("osc_2_distortion_amount", 0.36)]
case("mod_velocity_to_fm_carrier_level", "Velocity into the level of an FM carrier at level 0",
     OSC2_FM + [("osc_2_level", 0.0)], modulations=[("velocity", "osc_2_level", 0.5)])
case("mod_velocity_to_fm_carrier_level_static", "The level the velocity should give the carrier",
     OSC2_FM + [("osc_2_level", 0.45)])

# The FM / RM wiring, slot by slot: oscillator "A" of slot 1 is slot 2,
# of slots 2 and 3 it is slot 1; "B" is slot 3 for slots 1 and 2, slot 2
# for slot 3 (`ProducersModule::getFirst/SecondModulationIndex`); the
# third source is the SMP section's raw output. Spinwave wired every
# slot to the next one until Strings Section (osc 2 FM'd by osc 1)
# measured it (2026-09-13). The modulator sits a fifth up so the pair
# is audible as FM; the two other slots stay off. The FM pairs read
# 1.4e-6 rms, uniform over the note, where RM reads the floor: the
# modulator's own floor (1e-7, wavetable interpolation ulps) times the
# FM index (phase offset = modulation * amount * 6 cycles at 0.5) —
# the floor amplified, not a wiring or timing difference (which would
# read 1e-2 as it did before).
def fm_pair(carrier, modulator, name, dtype):
    on = [("osc_%d_on" % k, 1 if k in (carrier, modulator) else 0) for k in (1, 2, 3)]
    settings = [("filter_1_on", 0)] + on
    for k in (carrier, modulator):
        settings += [("osc_%d_random_phase" % k, 0), ("osc_%d_phase" % k, 0),
                     ("osc_%d_level" % k, 0.4)]
    settings += [("osc_%d_transpose" % modulator, 7.0),
                 ("osc_%d_distortion_type" % carrier, dtype),
                 ("osc_%d_distortion_amount" % carrier, 0.5)]
    case("osc_fm_wiring_" + name, "Slot %d %s slot %d" % (carrier, "FM'd by" if dtype < 10 else "RM'd by", modulator), settings)
fm_pair(1, 2, "1_from_a", 7)
fm_pair(1, 3, "1_from_b", 8)
fm_pair(2, 1, "2_from_a", 7)
fm_pair(2, 3, "2_from_b", 8)
fm_pair(3, 1, "3_from_a", 7)
fm_pair(3, 2, "3_from_b", 8)
fm_pair(3, 2, "3_rm_from_b", 11)
# A cycle: slot 1 FM'd by slot 2, slot 2 FM'd by slot 1. The reference's
# ordering loop never qualifies either, so neither renders: silence.
case("osc_fm_wiring_cycle", "Slots 1 and 2 FM'd by each other: neither renders",
     [("filter_1_on", 0), ("osc_2_on", 1), ("osc_2_random_phase", 0), ("osc_2_phase", 0),
      ("osc_2_level", 0.4), ("osc_1_distortion_type", 7), ("osc_1_distortion_amount", 0.5),
      ("osc_2_distortion_type", 7), ("osc_2_distortion_amount", 0.5)])

# VLT Future Gun (2.5 dB, 2026-09-13) bisected to env_2 -> lfo_2_tempo
# (a dotted-synced LFO, amount 0 but meta-modulated by a macro) with
# lfo_2 -> osc_3_transpose. Three cases pull it apart: the envelope into
# the tempo index heard on the cutoff; the same heard on the transpose
# (audio rate); the amount coming from a meta connection.
ENV_TEMPO = [("filter_1_on", 1), ("filter_1_model", 3), ("filter_1_cutoff", 60.0),
             ("filter_1_resonance", 0.4), ("lfo_1_sync", 2), ("lfo_1_tempo", 5.0),
             ("env_2_attack", 0.6), ("env_2_decay", 0.8), ("env_2_sustain", 0.5), ("env_2_release", 0.5)]
case("mod_env_to_lfo_tempo", "An envelope into a dotted-synced LFO's tempo, heard on the cutoff",
     ENV_TEMPO, modulations=[("env_2", "lfo_1_tempo", 0.3), ("lfo_1", "filter_1_cutoff", 0.4)])
case("mod_env_to_lfo_tempo_transpose", "The same LFO into osc 1 transpose (audio rate)",
     ENV_TEMPO, modulations=[("env_2", "lfo_1_tempo", 0.3), ("lfo_1", "osc_1_transpose", 0.3)])
case("mod_env_to_lfo_tempo_meta", "The envelope's amount on the tempo from a macro (0.3 * 0.5 * 2)",
     ENV_TEMPO + [("macro_control_3", 0.3)],
     modulations=[("env_2", "lfo_1_tempo", 0.0), ("lfo_1", "osc_1_transpose", 0.3),
                  ("macro_control_3", "modulation_1_amount", 0.5)])
# ... and the two together, as the preset has them: a macro into the
# same tempo, listed after the meta connection.
case("mod_env_and_macro_to_lfo_tempo", "An envelope (meta amount) and a macro into one LFO tempo",
     ENV_TEMPO + [("macro_control_3", 0.3), ("macro_control_1", 0.5)],
     modulations=[("env_2", "lfo_1_tempo", 0.0), ("lfo_1", "osc_1_transpose", 0.3),
                  ("macro_control_3", "modulation_1_amount", 0.5), ("macro_control_1", "lfo_1_tempo", 0.1475)])
case("mod_env_and_macro_to_lfo_tempo_no_meta", "The same without the meta connection (amount 0.3 set)",
     ENV_TEMPO + [("macro_control_1", 0.5)],
     modulations=[("env_2", "lfo_1_tempo", 0.3), ("lfo_1", "osc_1_transpose", 0.3),
                  ("macro_control_1", "lfo_1_tempo", 0.1475)])
# The listing order of the two, and a second envelope in place of the macro.
case("mod_macro_then_env_to_lfo_tempo", "The macro listed first, then the envelope, into one LFO tempo",
     ENV_TEMPO + [("macro_control_1", 0.5)],
     modulations=[("macro_control_1", "lfo_1_tempo", 0.1475), ("env_2", "lfo_1_tempo", 0.3),
                  ("lfo_1", "osc_1_transpose", 0.3)])
case("mod_two_envs_to_lfo_tempo", "Two envelopes into one LFO tempo",
     ENV_TEMPO + [("env_3_attack", 0.3), ("env_3_sustain", 0.8)],
     modulations=[("env_2", "lfo_1_tempo", 0.3), ("lfo_1", "osc_1_transpose", 0.3),
                  ("env_3", "lfo_1_tempo", 0.1475)])
case("mod_env_and_macro_to_lfo_frequency", "An envelope and a macro into one free LFO's frequency",
     [("filter_1_on", 1), ("filter_1_model", 3), ("filter_1_cutoff", 60.0), ("filter_1_resonance", 0.4),
      ("lfo_1_sync", 0), ("lfo_1_frequency", 1.0), ("macro_control_1", 0.5),
      ("env_2_attack", 0.6), ("env_2_decay", 0.8), ("env_2_sustain", 0.5), ("env_2_release", 0.5)],
     modulations=[("env_2", "lfo_1_frequency", 0.3), ("lfo_1", "osc_1_transpose", 0.3),
                  ("macro_control_1", "lfo_1_frequency", 0.1475)])
# The LFO's own connection listed first: only the macro's plug can then
# move lfo_1 ahead of the envelope's connection.
case("mod_lfo_first_env_and_macro_to_tempo", "lfo_1 -> transpose listed first, then env and macro into its tempo",
     ENV_TEMPO + [("macro_control_1", 0.5)],
     modulations=[("lfo_1", "osc_1_transpose", 0.3), ("env_2", "lfo_1_tempo", 0.3),
                  ("macro_control_1", "lfo_1_tempo", 0.1475)])

# -- Gate 3's second round (2026-09-13): one case per bank class the
# bisection left, named after the preset that raised it. ----------------

# Fun Pulse: a STEREO sample-and-hold random (`polyNext`, a draw per
# lane) tempo-synced into a cutoff.
case("bank_fun_pulse_stereo_random", "A stereo sample-and-hold random LFO into the cutoff (Fun Pulse)",
     RANDOM_FILTER + [("random_1_frequency", 3.0), ("random_1_style", 1), ("random_1_stereo", 1)],
     modulations=[("random_1", "filter_1_cutoff", 0.5)], random_seed=18)
# Remedial Shikari, Railgun: a modulator into osc_1_unison_voices - the
# voice count changing under a running note.
case("bank_remedial_lfo_to_unison_voices", "An LFO into the unison voice count (Remedial Shikari)",
     NO_FILTER + [("osc_1_unison_voices", 1), ("osc_1_unison_detune", 4.47), ("lfo_1_frequency", 1.0)],
     modulations=[("lfo_1", "osc_1_unison_voices", 1.0)])
case("bank_railgun_env_to_unison_voices", "An envelope into the unison voice count (Railgun)",
     NO_FILTER + [("osc_1_unison_voices", 1), ("osc_1_unison_detune", 4.47),
                  ("env_2_attack", 0.17), ("env_2_decay", 0.86), ("env_2_sustain", 0.0)],
     modulations=[("env_2", "osc_1_unison_voices", 1.0)])
# Cursed Steps: a bipolar sample-and-hold random into a macro, the macro
# into a transpose.
# (The preset holds the macro at 0 under a bipolar +-0.93: half of every
# draw is clamped. The case keeps the macro interior, 0.5 +- 0.2.)
case("bank_cursed_random_to_macro", "A bipolar sample-and-hold random into a macro into osc 1 transpose (Cursed Steps)",
     NO_FILTER + [("random_1_frequency", 3.0), ("random_1_style", 1), ("macro_control_2", 0.5)],
     modulations=[("random_1", "macro_control_2", 0.4, {"bipolar": 1}),
                  ("macro_control_2", "osc_1_transpose", 0.26)], random_seed=18)
# Crescendo Bells: an envelope-mode LFO (sync type 2, a delay) into a
# COMB filter's cutoff (model 6).
case("bank_crescendo_lfo_env_to_comb_cutoff", "An envelope-mode LFO with a delay into a comb filter's cutoff (Crescendo Bells)",
     [("filter_1_on", 1), ("filter_1_model", 6), ("filter_1_style", 0), ("filter_1_cutoff", 60.0),
      ("filter_1_resonance", 0.21), ("filter_1_blend_transpose", 49.98), ("filter_1_formant_resonance", 0.85),
      ("lfo_1_sync_type", 2), ("lfo_1_frequency", 1.0), ("lfo_1_delay_time", 0.4)],
     modulations=[("lfo_1", "filter_1_cutoff", 0.38)])
case("bank_crescendo_lfo_to_comb_cutoff", "A plain LFO into a comb filter's cutoff",
     [("filter_1_on", 1), ("filter_1_model", 6), ("filter_1_style", 0), ("filter_1_cutoff", 60.0),
      ("filter_1_resonance", 0.21), ("filter_1_blend_transpose", 49.98), ("filter_1_formant_resonance", 0.85),
      ("lfo_1_frequency", 1.0)],
     modulations=[("lfo_1", "filter_1_cutoff", 0.38)])
# Piano from the yard sale: the note into an audio-rate envelope's decay
# (the envelope feeds osc_1_level with a power), decay power -8.84.
case("bank_piano_note_to_env_decay", "The note into the decay of an envelope feeding osc 1 level with power (Piano from the yard sale)",
     NO_FILTER + [("osc_1_level", 0.0), ("env_2_attack", 0.0), ("env_2_decay", 0.88), ("env_2_decay_power", -8.84),
                  ("env_2_sustain", 0.0), ("env_2_release", 0.55)],
     modulations=[("env_2", "osc_1_level", 0.77, {"power": -0.4}),
                  ("note", "env_2_decay", -0.1, {"bipolar": 1})])
case("bank_piano_env_power_to_level", "The same envelope into osc 1 level with power, decay unmodulated",
     NO_FILTER + [("osc_1_level", 0.0), ("env_2_attack", 0.0), ("env_2_decay", 0.88), ("env_2_decay_power", -8.84),
                  ("env_2_sustain", 0.0), ("env_2_release", 0.55)],
     modulations=[("env_2", "osc_1_level", 0.77, {"power": -0.4})])
# Oolacile Evil Dubstep Bass: an envelope into voice_transpose.
case("bank_oolacile_env_to_voice_transpose", "An envelope into voice_transpose (Oolacile Evil Dubstep Bass)",
     NO_FILTER + [("env_2_attack", 0.15), ("env_2_decay", 0.79), ("env_2_decay_power", -2.0), ("env_2_sustain", 0.0)],
     modulations=[("env_2", "voice_transpose", -0.134)])
# Railgun: an envelope with decay power 6.6 into distortion_filter_cutoff.
case("bank_railgun_env_to_distortion_filter_cutoff", "An envelope (decay power 6.6) into distortion_filter_cutoff (Railgun)",
     [("filter_1_on", 0), ("distortion_on", 1), ("distortion_drive", 6.0), ("distortion_mix", 1.0),
      ("distortion_filter_order", 1), ("distortion_filter_cutoff", 60.0), ("distortion_filter_resonance", 0.5),
      ("env_2_attack", 0.15), ("env_2_decay", 0.95), ("env_2_decay_power", 6.6), ("env_2_sustain", 0.0)],
     modulations=[("env_2", "distortion_filter_cutoff", 1.0)])
# Phaser Entropy: an LFO into the phaser's control-rate mono controls.
# (The preset's negative amounts push these controls into their lower
# bounds; the cases keep them interior.)
for dest, base, amount in (("phaser_feedback", 0.4, 0.28), ("phaser_mod_depth", 24.0, 0.3),
                           ("phaser_phase_offset", 0.3, 0.3), ("phaser_blend", 0.5, 0.4)):
    case("bank_phaser_entropy_lfo_to_" + dest, "An LFO into " + dest + " (Phaser Entropy)",
         [("filter_1_on", 0), ("phaser_on", 1), ("phaser_dry_wet", 0.8), ("phaser_feedback", 0.6),
          (dest, base), ("lfo_1_frequency", 1.0)],
         modulations=[("lfo_1", dest, amount)])
case("bank_phaser_entropy_lfo_to_filter_fx_blend", "An LFO into filter_fx_blend and resonance (Phaser Entropy)",
     [("filter_1_on", 0), ("filter_fx_on", 1), ("filter_fx_cutoff", 60.0), ("filter_fx_resonance", 0.3),
      ("filter_fx_blend", 0.5), ("lfo_1_frequency", 1.0)],
     modulations=[("lfo_1", "filter_fx_blend", 0.4), ("lfo_1", "filter_fx_resonance", 0.3)])
# Dispersed Grit: a poly envelope into the mono filter_fx_cutoff with
# its amount from the velocity (a poly meta source), two voices of
# different velocities.
case("bank_dispersed_env_to_filter_fx_meta_velocity", "An envelope into filter_fx_cutoff, its amount from the velocity, two voices (Dispersed Grit)",
     [("filter_1_on", 0), ("filter_fx_on", 1), ("filter_fx_model", 1), ("filter_fx_style", 1),
      ("filter_fx_cutoff", 30.73), ("filter_fx_resonance", 0.5), ("filter_fx_keytrack", 1.0),
      ("filter_fx_blend_transpose", 42.0),
      ("env_2_attack", 0.43), ("env_2_decay", 1.0), ("env_2_sustain", 0.195), ("env_2_release", 0.55)],
     modulations=[("env_2", "filter_fx_cutoff", 0.0), ("velocity", "modulation_1_amount", 0.5)],
     extra_notes=[(52, 0.4, 1.15, 0.5)])
# Squish Clicker: the delay with its filter cutoff at the top bound and
# a spread, feedback 0.74, a macro opening the dry/wet.
case("bank_squish_delay_filter_top", "The delay with filter cutoff 136 (the bound) and spread 0.815 (Squish Clicker)",
     [("filter_1_on", 0), ("delay_on", 1), ("delay_dry_wet", 0.5), ("delay_feedback", 0.74),
      ("delay_filter_cutoff", 136.0), ("delay_filter_spread", 0.815), ("delay_sync", 0), ("delay_frequency", 5.08)],
     skip=LONG_SKIP)
case("bank_squish_delay_filter_interior", "The same delay with its filter cutoff interior (100)",
     [("filter_1_on", 0), ("delay_on", 1), ("delay_dry_wet", 0.5), ("delay_feedback", 0.74),
      ("delay_filter_cutoff", 100.0), ("delay_filter_spread", 0.815), ("delay_sync", 0), ("delay_frequency", 5.08)],
     skip=LONG_SKIP)
# A plain LFO into the cutoff of every filter model (the comb, model 6,
# read 6.4e-2 above where the digital model reads the floor).
for model, name in ((0, "analog"), (1, "dirty"), (2, "ladder"), (3, "digital"), (4, "diode"), (5, "formant"), (6, "comb"), (7, "phase")):
    case("mod_lfo_to_cutoff_model_" + name, "An LFO into the cutoff of the %s filter" % name,
         [("filter_1_on", 1), ("filter_1_model", model), ("filter_1_style", 0), ("filter_1_cutoff", 60.0),
          ("filter_1_resonance", 0.3), ("lfo_1_frequency", 1.0)],
         modulations=[("lfo_1", "filter_1_cutoff", 0.3)])
# ... the count's range narrowed: 1..4, 3..6, 6..9.
for base, amount, name in ((1, 0.2, "1_to_4"), (3, 0.2, "3_to_6"), (6, 0.2, "6_to_9")):
    case("bank_remedial_lfo_to_unison_voices_" + name, "An LFO into the unison voice count, %s (Remedial Shikari)" % name.replace("_", " "),
         NO_FILTER + [("osc_1_unison_voices", base), ("osc_1_unison_detune", 4.47), ("lfo_1_frequency", 1.0)],
         modulations=[("lfo_1", "osc_1_unison_voices", amount)])
# The filter fx running the comb under a moving cutoff.
case("mod_lfo_to_filter_fx_cutoff_comb", "An LFO into the filter fx's cutoff, comb model",
     [("filter_1_on", 0), ("filter_fx_on", 1), ("filter_fx_model", 6), ("filter_fx_style", 0),
      ("filter_fx_cutoff", 60.0), ("filter_fx_resonance", 0.3), ("lfo_1_frequency", 1.0)],
     modulations=[("lfo_1", "filter_fx_cutoff", 0.3)])
# Squish Clicker: an LFO into the delay time (delay_frequency).
case("bank_squish_lfo_to_delay_frequency", "An LFO into the delay's frequency (Squish Clicker)",
     [("filter_1_on", 0), ("delay_on", 1), ("delay_dry_wet", 0.5), ("delay_feedback", 0.74),
      ("delay_filter_cutoff", 100.0), ("delay_filter_spread", 0.815), ("delay_sync", 0), ("delay_frequency", 5.08),
      ("lfo_1_frequency", 1.0)],
     modulations=[("lfo_1", "delay_frequency", -0.38)], skip=LONG_SKIP)
# ... the same split: the random unipolar, and an LFO bipolar.
case("bank_cursed_random_to_macro_unipolar", "A unipolar sample-and-hold random into a macro into osc 1 transpose",
     NO_FILTER + [("random_1_frequency", 3.0), ("random_1_style", 1), ("macro_control_2", 0.3)],
     modulations=[("random_1", "macro_control_2", 0.4),
                  ("macro_control_2", "osc_1_transpose", 0.26)], random_seed=18)
case("bank_cursed_lfo_bipolar_to_macro", "A bipolar LFO into a macro into osc 1 transpose",
     NO_FILTER + [("lfo_1_frequency", 1.0), ("macro_control_2", 0.5)],
     modulations=[("lfo_1", "macro_control_2", 0.4, {"bipolar": 1}),
                  ("macro_control_2", "osc_1_transpose", 0.26)])
case("bank_cursed_lfo_to_macro_to_transpose", "A unipolar LFO into a macro into osc 1 transpose",
     NO_FILTER + [("lfo_1_frequency", 1.0), ("macro_control_2", 0.3)],
     modulations=[("lfo_1", "macro_control_2", 0.4),
                  ("macro_control_2", "osc_1_transpose", 0.26)])
# Memory Leak, THUNK: an LFO into voice_transpose - a block late where
# the envelope is same-block (the LFO reads the bent midi for its
# keytrack: a cycle the reference's router keeps lagged).
case("bank_memory_leak_lfo_to_voice_transpose", "An LFO into voice_transpose (Memory Leak)",
     NO_FILTER + [("lfo_1_frequency", 1.0)],
     modulations=[("lfo_1", "voice_transpose", 0.3)])
case("bank_memory_leak_random_to_voice_transpose", "A random LFO into voice_transpose",
     NO_FILTER + [("random_1_frequency", 1.0)],
     modulations=[("random_1", "voice_transpose", 0.3)], random_seed=18)
case("bank_oolacile_env_and_lfo_to_voice_transpose", "An envelope and an LFO into voice_transpose together",
     NO_FILTER + [("lfo_1_frequency", 1.0), ("env_2_attack", 0.15), ("env_2_decay", 0.79), ("env_2_sustain", 0.0)],
     modulations=[("env_2", "voice_transpose", -0.134), ("lfo_1", "voice_transpose", 0.2)])

print("wrote {} cases to {}".format(len(os.listdir(CASES)), CASES))
