#!/usr/bin/env python3
"""Writes the golden corpus: one case per thing worth pinning down.

Cases are small and mechanical, so they are generated rather than typed:
a table here beats forty near-identical files drifting apart by hand. Run
this whenever the corpus grows, then regenerate the references:

    python tools/golden/make_cases.py
    for c in tools/golden/cases/*.txt; do
        tools/golden/build/vital_golden "$c" \
            "tools/golden/reference/$(basename "${c%.txt}").raw"
    done

Two rules every case obeys, both learned the hard way:

* `random_phase 0` is mandatory. It defaults to 1, and two engines cannot
  agree sample for sample on a waveform that starts somewhere random.

* The first note is a primer that `skip` excludes. The reference scoops
  its very first note up from MIDI note 0 (its last-played-note starts at
  zero), which Spinwave deliberately does not reproduce; see the note in
  spinwave-engine/src/allocator.rs. Skipping the glide alone is not
  enough, because it leaves the two oscillators a fixed phase apart, so
  the primer has to be a whole note the next one resets the phase from.
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))
CASES = os.path.join(HERE, "cases")

PREAMBLE = """\
# {title}
#
# Generated by tools/golden/make_cases.py; edit that, not this.
rate 44100
seconds 2.0
skip 1.0
wave {wave}
set osc_1_on 1
set osc_1_level 0.7
set osc_1_random_phase 0
set osc_1_phase 0
"""

FOOTER = """\
note 45 0.9 0.0 0.3
note {note} 0.9 1.1 0.6
"""


def case(name, title, settings, wave="saw", note=45):
    """One case: a preamble, the settings under test, the two notes."""
    body = PREAMBLE.format(title=title, wave=wave)
    for key, value in settings:
        body += "set {} {}\n".format(key, value)
    body += FOOTER.format(note=note)
    with open(os.path.join(CASES, name + ".txt"), "w", newline="\n") as out:
        out.write(body)


# -- The corpus --------------------------------------------------------------

# The plain path first: if this diverges, nothing below means anything.
case("osc_saw_dry", "A bare saw: no filter, no effects, no modulation",
     [("filter_1_on", 0)])

# Every waveform the reference ships, through the same bare path. These
# pin the oscillator's band-limiting and its wavetable reading.
for wave in ("sin", "triangle", "square", "pulse"):
    case("osc_wave_" + wave, "A bare {} through the plain path".format(wave),
         [("filter_1_on", 0)], wave=wave)

# Phase distortion: the shapes that make Vital sound like Vital. Amount is
# held at 0.6 so each mode is doing real work rather than sitting near its
# neutral point.
PHASE_MODES = [
    (1, "sync"), (2, "formant"), (3, "quantize"), (4, "bend"),
    (5, "squeeze"), (6, "pulse_width"), (7, "fm_from_a"), (8, "fm_from_b"),
    (9, "rm_from_a"), (10, "rm_from_b"), (11, "phase_disperse"), (12, "fm_a_b"),
]
for index, name in PHASE_MODES:
    case("osc_warp_" + name,
         "Phase distortion mode {} ({})".format(index, name),
         [("filter_1_on", 0),
          ("osc_1_distortion_type", index),
          ("osc_1_distortion_amount", 0.6)])

# Spectral morphs, same idea: each mode at a working amount.
MORPH_MODES = [
    (1, "vocode"), (2, "formant_scale"), (3, "harmonic_stretch"),
    (4, "inharmonic_stretch"), (5, "smear"), (6, "random_amplitudes"),
    (7, "low_pass"), (8, "high_pass"), (9, "phase_disperse"),
    (10, "shepard"), (11, "spectral_time_skew"),
]
for index, name in MORPH_MODES:
    case("osc_morph_" + name,
         "Spectral morph mode {} ({})".format(index, name),
         [("filter_1_on", 0),
          ("osc_1_spectral_morph_type", index),
          ("osc_1_spectral_morph_amount", 0.6)])

# Unison: the detune law, the stereo spread and the voice stacking.
case("osc_unison", "Seven-voice unison, wide detune",
     [("filter_1_on", 0),
      ("osc_1_unison_voices", 7),
      ("osc_1_unison_detune", 6.0),
      ("osc_1_unison_blend", 0.7),
      ("osc_1_stereo_spread", 0.8)])

# Filters: every model, twice. Low resonance shows the response, high
# resonance shows the saturator and the feedback path.
FILTER_MODELS = [
    (0, "analog"), (1, "dirty"), (2, "ladder"), (3, "digital"),
    (4, "diode"), (5, "formant"), (6, "comb"), (7, "phaser"),
]
for index, name in FILTER_MODELS:
    for resonance, label in ((0.3, "low_q"), (0.85, "high_q")):
        case("filter_{}_{}".format(name, label),
             "Filter model {} ({}) at resonance {}".format(index, name, resonance),
             [("filter_1_on", 1),
              ("filter_1_model", index),
              ("filter_1_cutoff", 72.0),
              ("filter_1_resonance", resonance),
              ("filter_1_drive", 6.0)])

# Effects, one at a time, each with its dry/wet up so the effect is what
# the comparison is looking at.
EFFECTS = [
    ("chorus", [("chorus_dry_wet", 0.8)]),
    ("delay", [("delay_dry_wet", 0.8), ("delay_feedback", 0.5)]),
    ("distortion", [("distortion_drive", 12.0), ("distortion_mix", 1.0)]),
    ("eq", [("eq_low_gain", 8.0), ("eq_high_gain", -8.0)]),
    ("flanger", [("flanger_dry_wet", 0.8), ("flanger_feedback", 0.6)]),
    ("phaser", [("phaser_dry_wet", 0.8), ("phaser_feedback", 0.6)]),
    ("reverb", [("reverb_dry_wet", 0.8), ("reverb_decay_time", 1.0)]),
    ("compressor", [("compressor_mix", 1.0)]),
    ("filter_fx", [("filter_fx_cutoff", 70.0), ("filter_fx_resonance", 0.6)]),
]
for name, settings in EFFECTS:
    case("fx_" + name, "The {} effect on its own".format(name),
         [("filter_1_on", 0), (name + "_on", 1)] + settings)

# Envelope shapes: the quartic time scaling and the sustain law.
case("env_fast", "A short percussive envelope",
     [("filter_1_on", 0),
      ("env_1_attack", 0.0), ("env_1_decay", 0.35),
      ("env_1_sustain", 0.0), ("env_1_release", 0.2)])
case("env_slow", "A slow pad envelope",
     [("filter_1_on", 0),
      ("env_1_attack", 0.5), ("env_1_decay", 0.7),
      ("env_1_sustain", 0.8), ("env_1_release", 0.6)])

# NOT YET: the modulation matrix, which is where this week's worst bug
# lived. A connection is not a control on either side (the reference wires
# them through `connectModulation`), so the case format needs a
# `modulate <source> <dest> <amount>` directive and both harnesses need to
# honour it. That is the next thing the corpus wants.

# Pitch: a note two octaves up exercises the band-limiting hardest, where
# a mip-selection difference would show.
case("osc_high_note", "The same saw two octaves up, hardest on band-limiting",
     [("filter_1_on", 0)], note=69)

print("wrote {} cases to {}".format(len(os.listdir(CASES)), CASES))
